### ISSUE TITLE
GraphiteWriter is broken

### ISSUE THREAD

**Issue by phillipbroberts** [jmxtrans/jmxtrans#263]
StdOutWriter works fine, I get the expected results, when running GraphiteWriter I am seeing this: 

[30 Mar 2015 20:35:14] [main] 0      INFO  (com.googlecode.jmxtrans.JmxTransformer:134) - Starting Jmxtrans on : /var/lib/jmxtrans
[30 Mar 2015 20:35:14] [main] 273    DEBUG (com.googlecode.jmxtrans.JmxTransformer:354) - Loaded file: /var/lib/jmxtrans/web001.json
[30 Mar 2015 20:35:14] [main] 284    DEBUG (com.googlecode.jmxtrans.JmxTransformer:429) - Scheduled job: web001:8687-1427747714574-5479586537 for server: Server [host=web001, port=8687, url=null, cronExpression=null, numQueryThreads=null]
[30 Mar 2015 20:35:14] [ServerScheduler_Worker-1] 289    DEBUG (com.googlecode.jmxtrans.jobs.ServerJob:31) - +++++ Started server job: Server [host=web001, port=8687, url=null, cronExpression=null, numQueryThreads=null]
[30 Mar 2015 20:35:14] [ServerScheduler_Worker-1] 493    DEBUG (com.googlecode.jmxtrans.util.JmxUtils:195) - Executing queryName: java.lang:type=Memory from query: Query [obj=java.lang:type=Memory, resultAlias=heap, attr=[HeapMemoryUsage, NonHeapMemoryUsage]]
[30 Mar 2015 20:35:14] [ServerScheduler_Worker-1] 508    ERROR (com.googlecode.jmxtrans.jobs.ServerJob:39) - Error
java.util.NoSuchElementException: Could not create a validated object, cause: ValidateObject failed
        at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1256)
        at com.googlecode.jmxtrans.model.output.GraphiteWriter.doWrite(GraphiteWriter.java:105)
        at com.googlecode.jmxtrans.util.JmxUtils.runOutputWritersForQuery(JmxUtils.java:336)
        at com.googlecode.jmxtrans.util.JmxUtils.processQuery(JmxUtils.java:206)
        at com.googlecode.jmxtrans.util.JmxUtils.processQueriesForServer(JmxUtils.java:120)
        at com.googlecode.jmxtrans.util.JmxUtils.processServer(JmxUtils.java:456)
        at com.googlecode.jmxtrans.jobs.ServerJob.execute(ServerJob.java:37)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549)

I am running the latest RPM version as of today (just installed today, on CentOS 6.6)

Here is the config: 

{
  "servers" : [ {
    "port" : 8687,
    "host" : "web001",
    "queries" : [ {
      "outputWriters" : [{
        "@class" : "com.googlecode.jmxtrans.model.output.GraphiteWriter",
        "settings" : {
          "port" : 2003,
          "host" : "syslog"
        }
        }],
      "obj" : "java.lang:type=Memory",
      "resultAlias": "heap",
      "attr" : [ "HeapMemoryUsage", "NonHeapMemoryUsage" ]
    }, {
      "outputWriters" : [{
        "@class" : "com.googlecode.jmxtrans.model.output.GraphiteWriter",
        "settings" : {
          "port" : 2003,
          "host" : "syslog"
        }
        }]
      } ]
  } ]
}

**Comment by phillipbroberts** [comment]
I have tried a few different JDK's both Oracle and OpenJDK. Still getting the same problem.

**Comment by phillipbroberts** [comment]
I compiled from source with maven and the problem is gone. It was also gone in a previous RPM version. Closing because I think it is only limited to the current release rpm.

**Comment by gehel** [comment]
Glad to see you managed to solve your problem. Note that since yesterday, we have new RPM (and jars and everything) published to Maven central : http://central.maven.org/maven2/org/jmxtrans/jmxtrans/249/
