### ISSUE TITLE
NullPointerException in KafkaWriter

### ISSUE THREAD

**Issue by utkarshcmu** [jmxtrans/jmxtrans#310]
Bug found in the code.

KafkaWriter not reading topic list from the configuration file and hence throwing nullpointerexception.

Caused by: com.googlecode.jmxtrans.exceptions.LifecycleException: Error parsing json: /var/lib/jmxtrans/xyz.json
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.googlecode.jmxtrans.ConfigurationParser.parseServers(ConfigurationParser.java:36)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.googlecode.jmxtrans.JmxTransformer.processFilesIntoServers(JmxTransformer.java:310)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.googlecode.jmxtrans.JmxTransformer.startupSystem(JmxTransformer.java:277)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.googlecode.jmxtrans.JmxTransformer.start(JmxTransformer.java:142)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	... 8 more
INFO   | jvm 1    | 2015/07/01 08:52:37 | Caused by: com.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class com.googlecode.jmxtrans.model.output.kafka.KafkaWriter] value failed: null (through reference chain: com.googlecode.jmxtrans.model.JmxProcess["servers"]->java.util.ArrayList[0]->java.util.ArrayList[0]->java.util.ArrayList[0])
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapException(StdValueInstantiator.java:396)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:231)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:167)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:441)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1073)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:174)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:144)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:124)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:95)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:131)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:242)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:212)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:381)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1073)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:142)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:240)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:212)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:381)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1073)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:142)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:240)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:212)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:285)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:248)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2472)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.googlecode.jmxtrans.util.JsonUtils.getJmxProcess(JsonUtils.java:21)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.googlecode.jmxtrans.ConfigurationParser.parseServers(ConfigurationParser.java:25)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	... 11 more
INFO   | jvm 1    | 2015/07/01 08:52:37 | Caused by: java.lang.NullPointerException
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.googlecode.jmxtrans.model.output.kafka.KafkaWriter.<init>(KafkaWriter.java:80)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:125)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:227)
INFO   | jvm 1    | 2015/07/01 08:52:37 | 	... 48 more

**Comment by utkarshcmu** [comment]
This issue is fixed by #325 . Closing the issue.
