### ISSUE TITLE
InfluxDBWriter tries to create database

### ISSUE THREAD

**Issue by haraldkoch** [jmxtrans/jmxtrans#368]
The InfluxDBWriter calls "createDatabase". There is a comment that this creates the database if it does not exist.

Unfortunately, even when the database exists, InfluxDB (0.9.5.1) gives an error:

    java.lang.RuntimeException: {"error":"error authorizing query: jmxtrans not authorized to execute statement 'CREATE DATABASE IF NOT EXISTS jmxtrans', requires admin privilege"}
            at org.influxdb.impl.InfluxDBErrorHandler.handleError(InfluxDBErrorHandler.java:19) ~[jmxtrans-all.jar:na]
            at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:242) ~[jmxtrans-all.jar:na]
            at org.influxdb.impl.$Proxy19.query(Unknown Source) ~[na:na]
            at org.influxdb.impl.InfluxDBImpl.createDatabase(InfluxDBImpl.java:193) ~[jmxtrans-all.jar:na]
            at com.googlecode.jmxtrans.model.output.InfluxDbWriter.doWrite(InfluxDbWriter.java:151) ~[jmxtrans-all.jar:na]

The obvious fix is to comment out the 'createDatabase()' call; slightly more complicated would be to add a configuration switch.

(I'll try to make a pull request for this, but I don't know when I'll get around to it; I thought I'd put this here in case anyone else wants to dive in :)

**Comment by gehel** [comment]
@haraldkoch: could you have a look at #369 and see if this is what you were looking for?

**Comment by haraldkoch** [comment]
I did a quick review of the change and it seems legit.

I had a thought on the way home that would make for a better user experience, which would be to catch the exception and set a flag at runtime, but now that I'm looking at the issue again I see that InfluxDB throws a generic RuntimeException so that won't work. Too bad.

If you wait until tomorrow I can try this in my test environment...

**Comment by gehel** [comment]
No hurry, I'll wait until I have your feedback...

**Comment by haraldkoch** [comment]
worked perfectly; thanks!
