### ISSUE TITLE
Jersey query causes exception

### ISSUE THREAD

**Issue by jdudmesh** [jmxtrans/jmxtrans#421]
For the following query...

``` 
objectName=org.glassfish.jersey:type=reflow-ad-server,subType=Uris,resource="/router/bootstrap.js",executionTimes=RequestTimes
```

I'm getting the following in the log (snapshot 254)

```
[06 Feb 2016 18:51:36] [jmxtrans-query-5] 391    ERROR (com.googlecode.jmxtrans.jmx.ProcessQueryThread:57) - Error executing query Query(objectName=org.glassfish.jersey:type=reflow-ad-server,subType=Uris,resource="/router/bootstrap.js",executionTimes=RequestTimes, keys=[], attr=[AverageTime[ms]_1m, RequestRate[requestsPerSeconds]_1m], typeNames=[], resultAlias=null, useObjDomainAsKey=false, allowDottedKeys=false, useAllTypeNames=false, outputWriterInstances=[GraphiteWriter(pool=org.apache.commons.pool.impl.GenericKeyedObjectPool@2f30c5ba, rootPrefix=servers, address=localhost/127.0.0.1:2003, onlyOnceLogger=com.googlecode.jmxtrans.util.OnlyOnceLogger@5a1b7dae)]) on server Server(pid=null, host=log-emea-5, port=9091, url=service:jmx:rmi:///jndi/rmi://log-emea-5:9091/jmxrmi, cronExpression=null, numQueryThreads=0)
java.lang.NullPointerException
        at com.googlecode.jmxtrans.model.Query.fetchResults(Query.java:195)
        at com.googlecode.jmxtrans.model.Server.execute(Server.java:239)
        at com.googlecode.jmxtrans.jmx.ProcessQueryThread.run(ProcessQueryThread.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

```

The query works in jmxterm and simpler queries work in jmxtrans. I'm guessing that the quotes are causing the problem.

**Comment by jdudmesh** [comment]
It's the preceding line that's returning the null, which is then passed into line 195

```
AttributeList al = mbeanServer.getAttributes(queryName, attributes.toArray(new String[attributes.size()]));
```

These are the attributes I'm passing in:

```
					"attr": [
						"AverageTime[ms]_1m",
						"RequestRate[requestsPerSeconds]_1m"
					],
```
