### ISSUE TITLE
Need RPM with InfluxDbWriter support

### ISSUE THREAD

**Issue by kmumahesh** [jmxtrans/jmxtrans#454]
I downloaded the latest RPM from [here](https://github.com/jmxtrans/jmxtrans/downloads) (jmxtrans-20121016.145842.6a28c97fbb-0.noarch.rpm) but I'm getting class not found exception. I see from PR comments that influx db writer was merged only in Nov-Dec 2015, but the RPM is 4 years old. Is there a new RPM available somewhere?

```
Caused by: java.lang.IllegalArgumentException: Invalid type id 'com.googlecode.jmxtrans.model.output.InfluxDbWriterFactory' (for id type 'Id.class'): no such class found
        at org.codehaus.jackson.map.jsontype.impl.ClassNameIdResolver.typeFromId(ClassNameIdResolver.java:89)
        at org.codehaus.jackson.map.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:73)
        at org.codehaus.jackson.map.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:65)
        at org.codehaus.jackson.map.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:81)

```

**Comment by gehel** [comment]
Latest version can be found on [Maven Central](http://search.maven.org/#artifactdetails%7Corg.jmxtrans%7Cjmxtrans%7C254%7C) and latest SNAPSHOT on [Sonatype](https://oss.sonatype.org/content/repositories/snapshots/org/jmxtrans/jmxtrans/)

**Comment by kmumahesh** [comment]
Thanks! My bad, I missed it
