### ISSUE TITLE
Send influxdb error of partial write

### ISSUE THREAD

**Issue by jsvisa** [jmxtrans/jmxtrans#461]
Hi, I'm using this tool to report [Kafka metrics](http://kafka.apache.org/documentation.html#monitoring) to Influxdb, seems some error occured:

```bash
[17 May 2016 14:11:16] [jmxtrans-result-1] 600631 WARN  (com.googlecode.jmxtrans.jmx.ResultProcessor$1:60) - Could not write results [Result(attributeName=Count, className=com.yammer.metrics.reporting.JmxReporter$Meter, objDomain=kafka.server, typeName=type=BrokerTopicMetrics,name=TotalFetchRequestsPerSec, values={Count=11959345911}, epoch=1463465476260, keyAlias=TotalFetchRequestsPerSec), Result(attributeName=FiveMinuteRate, className=com.yammer.metrics.reporting.JmxReporter$Meter, objDomain=kafka.server, typeName=type=BrokerTopicMetrics,name=TotalFetchRequestsPerSec, values={FiveMinuteRate=12891.797552683302}, epoch=1463465476260, keyAlias=TotalFetchRequestsPerSec), Result(attributeName=EventType, className=com.yammer.metrics.reporting.JmxReporter$Meter, objDomain=kafka.server, typeName=type=BrokerTopicMetrics,name=TotalFetchRequestsPerSec, values={EventType=requests}, epoch=1463465476260, keyAlias=TotalFetchRequestsPerSec), Result(attributeName=RateUnit, className=com.yammer.metrics.reporting.JmxReporter$Meter, objDomain=kafka.server, typeName=type=BrokerTopicMetrics,name=TotalFetchRequestsPerSec, values={RateUnit=SECONDS}, epoch=1463465476260, keyAlias=TotalFetchRequestsPerSec), Result(attributeName=MeanRate, className=com.yammer.metrics.reporting.JmxReporter$Meter, objDomain=kafka.server, typeName=type=BrokerTopicMetrics,name=TotalFetchRequestsPerSec, values={MeanRate=7047.305165084382}, epoch=1463465476260, keyAlias=TotalFetchRequestsPerSec), Result(attributeName=OneMinuteRate, className=com.yammer.metrics.reporting.JmxReporter$Meter, objDomain=kafka.server, typeName=type=BrokerTopicMetrics,name=TotalFetchRequestsPerSec, values={OneMinuteRate=12897.022608154302}, epoch=1463465476260, keyAlias=TotalFetchRequestsPerSec), Result(attributeName=FifteenMinuteRate, className=com.yammer.metrics.reporting.JmxReporter$Meter, objDomain=kafka.server, typeName=type=BrokerTopicMetrics,name=TotalFetchRequestsPerSec, values={FifteenMinuteRate=12802.016890712133}, epoch=1463465476260, keyAlias=TotalFetchRequestsPerSec)] of query Query(objectName=kafka.server:type=BrokerTopicMetrics,name=TotalFetchRequestsPerSec, keys=[], attr=[Count, FiveMinuteRate, EventType, RateUnit, MeanRate, OneMinuteRate, FifteenMinuteRate], typeNames=[], resultAlias=TotalFetchRequestsPerSec, useObjDomainAsKey=false, allowDottedKeys=false, useAllTypeNames=false, outputWriterInstances=[com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter@6764459f]) to output writer com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter@6764459f
java.lang.RuntimeException: {"error":"partial write:\nunable to parse 'TotalFetchRequestsPerSec,attributeName=RateUnit,hostname=192.168.30.10,typeName=type\\=BrokerTopicMetrics\\,name\\=TotalFetchRequestsPerSec RateUnit=SECONDS,_jmx_port=9999.0 1463465476260000000': invalid boolean"}

        at org.influxdb.impl.InfluxDBErrorHandler.handleError(InfluxDBErrorHandler.java:19)
        at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:242)
        at org.influxdb.impl.$Proxy24.writePoints(Unknown Source)
        at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:161)
        at com.googlecode.jmxtrans.model.output.InfluxDbWriter.doWrite(InfluxDbWriter.java:167)
        at com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter.doWrite(ResultTransformerOutputWriter.java:61)
        at com.googlecode.jmxtrans.jmx.ResultProcessor$1.run(ResultProcessor.java:58)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by gehel** [comment]
It seems that the `RateUnit` attribute is causing the issue. I'm not an expert in InfluxDB, but I think it does only support numeric values. `RateUnit=SECONDS` is probably unsupported. The influxDB writer is not filtering non-numeric values, which should be considered as a bug...

Side note: I think that you do not need to escape the InfluxDB URL (`http:\/\/192.168.1.158:8086\/` could be just `http://192.168.1.158:8086/`).

**Comment by jsvisa** [comment]
@gehel Thanks for your advise, I'll consider for a PR later.

**Comment by anshitabharti** [comment]
@jsvisa i see the same error. Is it fixed ?
