### ISSUE TITLE
YAML outputWriter config for GraphiteWriterFactory requires "settings" key

### ISSUE THREAD

**Issue by vemod** [jmxtrans/jmxtrans#484]
1. When using `outputWriters` configuration in YAML `settings` wrapper key is required. Thus produced JSON config for GraphiteWriterFactory outputWriter is created wrong. 
   `com.googlecode.jmxtrans.model.output.GraphiteWriterFactory` doens't support `settings: {}` wrapper
2. Documentation is also outdated and doesn't provide required information about outputWriters configuration.
## 

At the moment 

```
outputWriters: 
    - "@class": "com.googlecode.jmxtrans.model.output.GraphiteWriterFactory"
      settings:
        host: "graphite"
        port: "2003"
        flushStrategy: "always"
        rootPrefix: "servers"
```

produces

```
"outputWriters": [
      {
       "@class": "com.googlecode.jmxtrans.model.output.GraphiteWriterFactory",
       "settings": {
        "flushStrategy": "always",
        "typeNames": [
         "name"
        ],
        "host": "graphite",
        "port": "2003",
        "rootPrefix": "servers"
       }
      }
```

BUT `com.googlecode.jmxtrans.model.output.GraphiteWriterFactory` expects the configuration without `settings: {}` wrapper. 

So when `settings:` wrapper is skipped following exception is thrown

```
Traceback (most recent call last):
  File "../yaml2jmxtrans.py", line 280, in <module>
    servers = q.create_host_set_configuration(s['hosts'],s['query_names'], query_port, s['username'], s['password'], s['urlTemplate'], set_name, global_host_alias)
  File "../yaml2jmxtrans.py", line 173, in create_host_set_configuration
    root['servers'].append(self.create_host_entry(host, query_names, port, username, password, urlTemplate, alias, set_name, rootPrefix))
  File "../yaml2jmxtrans.py", line 126, in create_host_entry
    hostentry['queries'].append(self.create_query_entry(query_name, rootPrefix))
  File "../yaml2jmxtrans.py", line 114, in create_query_entry
    queryentry['outputWriters'] = self.create_output_writer_configuration(typeName, rootPrefix)
  File "../yaml2jmxtrans.py", line 200, in create_output_writer_configuration
    writer[iter]['settings']['typeNames'] = typeNames
TypeError: 'NoneType' object does not support item assignment
```

Expected YAML: 

```
outputWriters: 
    - "@class": "com.googlecode.jmxtrans.model.output.GraphiteWriterFactory"
        host: "graphite"
        port: "2003"
        flushStrategy: "always"
        rootPrefix: "servers"
```

to produce JSON:

```
"outputWriters": [
      {
       "@class": "com.googlecode.jmxtrans.model.output.GraphiteWriterFactory",
        "flushStrategy": "always",
        "typeNames": [
         "name"
        ],
        "host": "${graphite_host}",
        "port": "${graphite_port}",
        "rootPrefix": "servers"
      }
```

**Comment by mcouillard** [comment]
Will this fix get into a versioned release?

**Comment by gehel** [comment]
It looks like this has been merged to master in Nov 2016 and thus should have been part of all releases since then. Looking at current master, the change look like they are actually there...

I'm closing this as it should have been closed a long time ago...
