### ISSUE TITLE
Cannot handle to write attr LastGcInfo to influxdb

### ISSUE THREAD

**Issue by metebilgin** [jmxtrans/jmxtrans#486]
Hello,
I am trying to write G1 Old Generation, G1 Young Generation LastGcInfo attr information to influxdb. it has comp-attr inside. And i cannot see an example about it.
Error:

```
        at org.influxdb.impl.InfluxDBErrorHandler.handleError(InfluxDBErrorHandler.java:19)
        at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:242)
        at org.influxdb.impl.$Proxy29.writePoints(Unknown Source)
        at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:151)
        at com.googlecode.jmxtrans.model.output.InfluxDbWriter.doWrite(InfluxDbWriter.java:174)
        at com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter.doWrite(ResultTransformerOutputWriter.java:50)
        at com.googlecode.jmxtrans.jmx.ResultProcessor$1.run(ResultProcessor.java:58)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```
Json file:
```
{
  "servers" : [
   {
    "port" : "123456",
    "host" : "localhost",
    "username" : "xyz",
    "password": "password",
    "queries" : [
    {
      "outputWriters" : [
        {
                "@class" : "com.googlecode.jmxtrans.model.output.InfluxDbWriterFactory",
                "url" : "http://127.0.0.1:8086/",
                "database" : "Test1",
                "username" : "jmxdb",
                "password" : "jmxdb"
        }
     ],
      "obj" : "java.lang:type=GarbageCollector,name=*",
      "resultAlias": "gc",
      "attr" : [ "CollectionCount", "CollectionTime", "LastGcInfo"]
    }
    ]
  } ]
}

```

**Comment by luvs** [comment]
+1 After update to InfluxDB 1.0 get error

`[10 Sep 2016 12:56:42] [jmxtrans-result-1] 46257  WARN  (com.googlecode.jmxtrans.jmx.ResultProcessor$1:60) - Could not write results [Result(attributeName=ProcessCpuTime, className=com.sun.management.UnixOperatingSystem, objDomain=java.lang, typeName=type=OperatingSystem, values={ProcessCpuTime=17825240000000}, epoch=1473501402380, keyAlias=jvmOS), Result(attributeName=SystemLoadAverage, className=com.sun.management.UnixOperatingSystem, objDomain=java.lang, typeName=type=OperatingSystem, values={SystemLoadAverage=0.15}, epoch=1473501402380, keyAlias=jvmOS), Result(attributeName=ProcessCpuLoad, className=com.sun.management.UnixOperatingSystem, objDomain=java.lang, typeName=type=OperatingSystem, values={ProcessCpuLoad=0.018802054760361078}, epoch=1473501402380, keyAlias=jvmOS)] of query Query(objectName=java.lang:type=OperatingSystem, keys=[], attr=[ProcessCpuTime, SystemLoadAverage, ProcessCpuLoad], typeNames=[], resultAlias=jvmOS, useObjDomainAsKey=false, allowDottedKeys=false, useAllTypeNames=false, outputWriterInstances=[com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter@7a99d0af]) to output writer com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter@7a99d0af
java.lang.RuntimeException: {"error":"error parsing query: found NOT, expected ; at line 1, char 20"}

        at org.influxdb.impl.InfluxDBErrorHandler.handleError(InfluxDBErrorHandler.java:19)
        at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:242)
        at org.influxdb.impl.$Proxy27.query(Unknown Source)
        at org.influxdb.impl.InfluxDBImpl.createDatabase(InfluxDBImpl.java:205)
        at com.googlecode.jmxtrans.model.output.InfluxDbWriter.doWrite(InfluxDbWriter.java:151)
        at com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter.doWrite(ResultTransformerOutputWriter.java:50)
        at com.googlecode.jmxtrans.jmx.ResultProcessor$1.run(ResultProcessor.java:58)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
`

**Comment by lewg** [comment]
The workaround is to set createDatabase to false in the settings, and make sure the database and retention policy that you're writing to already exists. Influx removed the 'IF NOT EXISTS' syntax in 1.0.0

**Comment by lewg** [comment]
The fix, I believe, is for the project to upgrade to the latest influxdb-java library.
