### ISSUE TITLE
JMXTRANS Could not write results to opentsdb

### ISSUE THREAD

**Issue by neerajtiwar** [jmxtrans/jmxtrans#487]
I am using JMXTRANS to collect jmx data and sending it to Opentsdb but i am getting error in the logs as below:-

```
[06 Sep 2016 18:37:58] [jmxtrans-result-0] 5013808 WARN  (com.googlecode.jmxtrans.jmx.ResultProcessor$1:60) - Could not write results [Result(attributeName=Usage, className=sun.management.MemoryPoolImpl, objDomain=java.lang, typeName=type=MemoryPool,name=Metaspace, values={init=0, committed=20185088, max=-1, used=19294632}, epoch=1473167278889, keyAlias=memorypool), Result(attributeName=Usage, className=sun.management.MemoryPoolImpl, objDomain=java.lang, typeName=type=MemoryPool,name=PS Old Gen, values={init=87031808, committed=87031808, max=1375731712, used=16730040}, epoch=1473167278890, keyAlias=memorypool), Result(attributeName=Usage, className=sun.management.MemoryPoolImpl, objDomain=java.lang, typeName=type=MemoryPool,name=PS Eden Space, values={init=32505856, committed=24117248, max=686817280, used=1818808}, epoch=1473167278894, keyAlias=memorypool), Result(attributeName=Usage, className=sun.management.MemoryPoolImpl, objDomain=java.lang, typeName=type=MemoryPool,name=Compressed Class Space, values={init=0, committed=2359296, max=1073741824, used=2134656}, epoch=1473167278896, keyAlias=memorypool), Result(attributeName=Usage, className=sun.management.MemoryPoolImpl, objDomain=java.lang, typeName=type=MemoryPool,name=Code Cache, values={init=2555904, committed=9633792, max=251658240, used=9240192}, epoch=1473167278898, keyAlias=memorypool), Result(attributeName=Usage, className=sun.management.MemoryPoolImpl, objDomain=java.lang, typeName=type=MemoryPool,name=PS Survivor Space, values={init=5242880, committed=524288, max=524288, used=294912}, epoch=1473167278900, keyAlias=memorypool)] of query Query(objectName=java.lang:type=MemoryPool,name=*, keys=[], attr=[Usage], typeNames=[], resultAlias=memorypool, useObjDomainAsKey=false, allowDottedKeys=false, useAllTypeNames=false, outputWriterInstances=[BaseOutputWriter(typeNames=[], debugEnabled=false, settings={host=10.143.1.43, port=4242}, valueTransformer=com.googlecode.jmxtrans.model.results.IdentityValueTransformer@35a68c72), BaseOutputWriter(typeNames=[], debugEnabled=false, settings={}, valueTransformer=com.googlecode.jmxtrans.model.results.IdentityValueTransformer@3b6164b6)]) to output writer BaseOutputWriter(typeNames=[], debugEnabled=false, settings={host=10.143.1.43, port=4242}, valueTransformer=com.googlecode.jmxtrans.model.results.IdentityValueTransformer@35a68c72)
java.lang.NullPointerException
	at com.googlecode.jmxtrans.model.output.support.opentsdb.OpenTSDBMessageFormatter.processOneMetric(OpenTSDBMessageFormatter.java:196)
	at com.googlecode.jmxtrans.model.output.support.opentsdb.OpenTSDBMessageFormatter.formatResult(OpenTSDBMessageFormatter.java:159)
	at com.googlecode.jmxtrans.model.output.support.opentsdb.OpenTSDBMessageFormatter.access$000(OpenTSDBMessageFormatter.java:54)
	at com.googlecode.jmxtrans.model.output.support.opentsdb.OpenTSDBMessageFormatter$1.apply(OpenTSDBMessageFormatter.java:170)
	at com.googlecode.jmxtrans.model.output.support.opentsdb.OpenTSDBMessageFormatter$1.apply(OpenTSDBMessageFormatter.java:166)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:817)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:569)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:249)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:209)
	at com.google.common.collect.FluentIterable.toList(FluentIterable.java:484)
	at com.googlecode.jmxtrans.model.output.support.opentsdb.OpenTSDBMessageFormatter.formatResults(OpenTSDBMessageFormatter.java:173)
	at com.googlecode.jmxtrans.model.output.OpenTSDBWriter.internalWrite(OpenTSDBWriter.java:116)
	at com.googlecode.jmxtrans.model.output.BaseOutputWriter.doWrite(BaseOutputWriter.java:157)
	at com.googlecode.jmxtrans.jmx.ResultProcessor$1.run(ResultProcessor.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

## My Config.Json looks like below:-

```
{
  "servers": [
    {
      "numQueryThreads": "2",
      "host": "xx.xx.xx.xx", 
      "port": "1099", 
      "queries": [ 
        {
          "outputWriters": [ 
            {
              "@class": "com.googlecode.jmxtrans.model.output.StdOutWriter" 
            },
            {
              "@class": "com.googlecode.jmxtrans.model.output.OpenTSDBWriter", 
              "settings": {
                "host": "xx.xx.xx.xx", 
                "port": "4242" 
              }
            }
          ],
          "obj": "java.lang:type=OperatingSystem", 
          "attr": [ 
            "SystemLoadAverage",
            "AvailableProcessors",
            "TotalPhysicalMemorySize",
            "FreePhysicalMemorySize",
            "TotalSwapSpaceSize",
            "FreeSwapSpaceSize",
            "OpenFileDescriptorCount",
            "MaxFileDescriptorCount"
          ]
        },
        {
          "outputWriters": [
            {
              "@class": "com.googlecode.jmxtrans.model.output.StdOutWriter"
            },
            {
              "@class": "com.googlecode.jmxtrans.model.output.OpenTSDBWriter",
              "settings": {
                "host": "xx.xx.xx.xx",
                "port": "4242"
              }
            }
          ],
          "resultAlias": "heap",
          "obj": "java.lang:type=Memory",
          "attr": [
            "HeapMemoryUsage",
            "NonHeapMemoryUsage"
          ]
        },
        {
          "outputWriters": [
            {
              "@class": "com.googlecode.jmxtrans.model.output.StdOutWriter"
            },
            {
              "@class": "com.googlecode.jmxtrans.model.output.OpenTSDBWriter",
              "settings": {
                "host": "xx.xx.xx.xx",
                "port": "4242"
              }
            }
          ],
          "resultAlias": "cmsoldgen",
          "obj": "java.lang:name=CMS Old Gen,type=MemoryPool",
          "attr": [
            "Usage"
          ]
        },
        {
          "outputWriters": [
            {
              "@class": "com.googlecode.jmxtrans.model.output.StdOutWriter"
            },
            {
              "@class": "com.googlecode.jmxtrans.model.output.OpenTSDBWriter",
              "settings": {
                "host": "xx.xx.xx.xx",
                "port": "4242"
              }
            }
          ],
          "resultAlias": "gc",
          "obj": "java.lang:type=GarbageCollector,name=*",
          "attr": [
            "CollectionCount",
            "CollectionTime"
          ]
        },
        {
          "outputWriters": [
            {
              "@class": "com.googlecode.jmxtrans.model.output.StdOutWriter",
              "settings": {}
            },
            {
              "@class": "com.googlecode.jmxtrans.model.output.OpenTSDBWriter",
              "settings": {
                "host": "xx.xx.xx.xx",
                "port": "4242"
              }
            }
          ],
          "resultAlias": "memorypool",
          "obj": "java.lang:type=MemoryPool,name=*",
          "attr": [
            "Usage"
          ]
        },
        {
          "outputWriters": [
            {
              "@class": "com.googlecode.jmxtrans.model.output.StdOutWriter"
            },
            {
              "@class": "com.googlecode.jmxtrans.model.output.OpenTSDBWriter",
              "settings": {
                "host": "xx.xx.xx.xx",
                "port": "4242"
              }
            }
          ],
          "resultAlias": "threads",
          "obj": "java.lang:type=Threading",
          "attr": [
            "DaemonThreadCount",
            "PeakThreadCount",
            "ThreadCount",
            "TotalStartedThreadCount"
          ]
        },
        {
          "outputWriters": [
            {
              "@class": "com.googlecode.jmxtrans.model.output.StdOutWriter"
            },
            {
              "@class": "com.googlecode.jmxtrans.model.output.OpenTSDBWriter",
              "settings": {
                "host": "xx.xx.xx.xx",
                "port": "4242"
              }
            }
          ],
          "resultAlias": "tomcat8-connectors",
          "obj": "Catalina:type=ThreadPool,name=*",
          "attr": [
            "currentThreadCount",
            "currentThreadsBusy"
          ]
        },
        {
          "outputWriters": [
            {
              "@class": "com.googlecode.jmxtrans.model.output.StdOutWriter"
            },
            {
              "@class": "com.googlecode.jmxtrans.model.output.OpenTSDBWriter",
              "settings": {
                "host": "xx.xx.xx.xx",
                "port": "4242"
              }
            }
          ],
          "resultAlias": "tomcat8-requests",
          "obj": "Catalina:type=GlobalRequestProcessor,name=*",
          "attr": [
            "bytesReceived",
            "bytesSent",
            "errorCount",
            "processingTime",
            "requestCount"
          ]
        }
      ]
    }
  ]
}
```

**Comment by gehel** [comment]
I have no idea how that NPE could happen, at least on latest release. Could you confirm which version you are using?

**Comment by derkyjadex** [comment]
I had this problem too. Looking at the offending line at [OpenTSDBMessageFormatter.java:196](https://github.com/jmxtrans/jmxtrans/blob/master/jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/support/opentsdb/OpenTSDBMessageFormatter.java#L196) it looks like it isn't checking whether `typeNames` is `null` (or it's not being defaulted to an empty list elsewhere).

A workaround for this is to add `"typeNames": []` to the OpenTSDBWriter settings. At least this is working for me and giving the results I'm expecting.
