### ISSUE TITLE
"error parsing query" while writing to InfluxDB

### ISSUE THREAD

**Issue by daniccan** [jmxtrans/jmxtrans#489]
I am getting the following error while trying to write to InfluxDB using jmxtrans.

java.lang.RuntimeException: {"error":"error parsing query: found NOT, expected ; at line 1, char 20"}

```
at org.influxdb.impl.InfluxDBErrorHandler.handleError(InfluxDBErrorHandler.java:19)
at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:242)
at org.influxdb.impl.$Proxy27.query(Unknown Source)
at org.influxdb.impl.InfluxDBImpl.createDatabase(InfluxDBImpl.java:205)
at com.googlecode.jmxtrans.model.output.InfluxDbWriter.doWrite(InfluxDbWriter.java:151)
at com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter.doWrite(ResultTransformerOutputWriter.java:50)
at com.googlecode.jmxtrans.jmx.ResultProcessor$1.run(ResultProcessor.java:58)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:744)
```

My InfluxDB version is 1.0.0. 

Following is the example.json I am using,

{
  "servers" : [ {
    "port" : "1099",
    "host" : "localhost",
    "queries" : [ {
      "obj" : "java.lang:type=Memory",
      "attr" : [ "HeapMemoryUsage", "NonHeapMemoryUsage" ],
      "resultAlias":"jvmMemory",
      "outputWriters" : [ {
        "@class" : "com.googlecode.jmxtrans.model.output.InfluxDbWriterFactory",
        "url" : "http://localhost:8086/",
        "database" : "mydb",
        "username" : "influxuser"
      } ]
    } ]
  } ]
}

**Comment by saad373** [comment]
I fixed this by providing "retentionPolicy":"autogen" in influxDB configuration.

**Comment by lewg** [comment]
The workaround is to set createDatabase to false in the settings, and make sure the database and retention policy that you're writing to already exists. Influx removed the 'IF NOT EXISTS' syntax in 1.0.0

**Comment by akhan4u** [comment]
Hi  i am facing the same issue as above, did the necessary changes as above. but still not able to do a workaround. please help

**Comment by gehel** [comment]
@akhan4u which version are you using? Can you post an example of your failing config?

**Comment by gehel** [comment]
Oh, I see you have posted them on #574. Let's continue the conversation there and close this ticket in the meantime...
