### ISSUE TITLE
ResultProcessor NPEs after running for a while

### ISSUE THREAD

**Issue by IvanVergiliev** [jmxtrans/jmxtrans#511]
After running perfectly fine for a while, jmxtrans stops writing metrics to the output writer. I see this error in the logs multiple times (I'm assuming for each attempted query):

```
[06 Nov 2016 23:16:08] [jmxtrans-result-5] 197814012 WARN  (com.googlecode.jmxtrans.jmx.ResultProcessor$1:60) - Could not write results [Result(attributeName=OneMinuteRate, className=com.yammer.metrics.reporting.JmxReporter$Meter, objDomain=kafka.server, typeName=type=ReplicaManager,name=IsrShrinksPerSec, values={OneMinuteRate=0.0}, epoch=1478474167305, keyAlias=replication.isr.shrink)] of query Query(objectName=kafka.server:type=ReplicaManager,name=IsrShrinksPerSec, keys=[], attr=[OneMinuteRate], typeNames=[], resultAlias=replication.isr.shrink, useObjDomainAsKey=false, allowDottedKeys=false, useAllTypeNames=false, outputWriterInstances=[]) to output writer com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter@2505453a
java.lang.NullPointerException
        at com.googlecode.jmxtrans.model.output.support.WriterPoolOutputWriter.doWrite(WriterPoolOutputWriter.java:59)
        at com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter.doWrite(ResultTransformerOutputWriter.java:50)
        at com.googlecode.jmxtrans.jmx.ResultProcessor$1.run(ResultProcessor.java:58)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

A few lines before the first such occurrence, I found this error:

```
[06 Nov 2016 23:16:07] [jmxtrans-result-0] 197813012 ERROR (com.googlecode.jmxtrans.model.output.support.pool.WriterPoolable:57) - Could not flush writer
java.net.SocketException: Connection reset
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
        at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at java.io.BufferedWriter.flush(BufferedWriter.java:254)
        at com.googlecode.jmxtrans.model.output.support.pool.TimeBasedFlush.flush(TimeBasedFlush.java:51)
        at com.googlecode.jmxtrans.model.output.support.pool.WriterPoolable.release(WriterPoolable.java:54)
        at com.googlecode.jmxtrans.model.output.support.WriterPoolOutputWriter.doWrite(WriterPoolOutputWriter.java:59)
        at com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter.doWrite(ResultTransformerOutputWriter.java:50)
        at com.googlecode.jmxtrans.jmx.ResultProcessor$1.run(ResultProcessor.java:58)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

So I'm assuming that this is caused by some form of network failure, and then the connections are not cleared properly or something like that. I tried digging into the code, but there are a bit too many layers of abstraction for me to figure something out quickly.

I'm using jmxtrans-259 with the `GraphiteOutputWriter` - let me know if you need any other details. Thanks in advance!

**Comment by gehel** [comment]
From the stacktrace, I suspect that you are using `GraphiteWriterFactory`. Could you confirm? Also, does this recover after some time?

This looks like a bug in stormpot, maybe @chrisvest knows something more about it (I know it is too easy to blame someone else... sorry Chris).

**Comment by IvanVergiliev** [comment]
Yep, that's correct - I'm using `GraphiteWriterFactory`. I haven't seen it recover yet - it's been like this for days at a time. It works fine once again after I restart it.

I assumed this could be something with the pool's `release` and `invalidate` calls. Let me know if I can help investigate somehow.

**Comment by chrisvest** [comment]
I don't see how this can be a bug in Stormpot. In 259 you call `release` on the result of a `claim` without first checking if it is `null`, and `null` is a valid return value when the claim times out: https://github.com/jmxtrans/jmxtrans/blob/jmxtrans-parent-259/jmxtrans-output/jmxtrans-output-core/src/main/java/com/googlecode/jmxtrans/model/output/support/WriterPoolOutputWriter.java

**Comment by gehel** [comment]
@chrisvest as always, my bad, sorry for the bother... The NPE is actually already fixed in the latest jmxtrans SNAPSHOT. I still need to understand why the connection isn't recovering. I'll dig deeper...

**Comment by gehel** [comment]
This should be fixed in latest SNAPSHOT by 089f4e5d87e9f4e016ec1de25dbc434bb2dc6935 (thanks to @kevinconaway). I'm closing this, feel free to re-open if it isn't fixed yet. I'll prepare a new release as well, it seems that it is time...

**Comment by IvanVergiliev** [comment]
Thanks for the quick response and the timely new release - `jmxtrans` been working fine for about 20 hours now! So closing this for the time being.

**Comment by gehel** [comment]
Thanks for the report! I should probably release jmxtrans more often...
