### ISSUE TITLE
com.fasterxml.jackson.databind.JsonMappingException

### ISSUE THREAD

**Issue by veerareddyganta** [jmxtrans/jmxtrans#518]
I am getting 'The username may not be null or empty' error message when I started jmxtrans using the following command.  

./jmxtrans.sh start ~/jmx_influx.json

**json file content:**
```
{
  "servers" : [ {
    "port" : "8999",
    "host" : "10.10.90.54",
    "username" : "vganta",
    "queries" : [ {
      "obj" : "java.lang:type=Memory",
      "attr" : [ "HeapMemoryUsage", "NonHeapMemoryUsage" ],
      "resultAlias":"jvmMemory",
      "outputWriters" : [ {
        "@class" : "com.googlecode.jmxtrans.model.output.InfluxDbWriterFactory",
        "url" : "http://10.10.90.54:8086/",
        "database" : "jmxDB"
      } ]
    } ]
  } ]
}
```

**Logs:**

```
[17 Nov 2016 16:24:22] [main] 167    ERROR (com.googlecode.jmxtrans.JmxTransformer:190) - Error parsing json: /home/vganta/jmx_influx.json
com.googlecode.jmxtrans.exceptions.LifecycleException: Error parsing json: /home/vganta/jmx_influx.json
        at com.googlecode.jmxtrans.ConfigurationParser.parseServers(ConfigurationParser.java:62)
        at com.googlecode.jmxtrans.JmxTransformer.processFilesIntoServers(JmxTransformer.java:354)
        at com.googlecode.jmxtrans.JmxTransformer.startupSystem(JmxTransformer.java:322)
        at com.googlecode.jmxtrans.JmxTransformer.start(JmxTransformer.java:187)
        at com.googlecode.jmxtrans.JmxTransformer.doMain(JmxTransformer.java:157)
        at com.googlecode.jmxtrans.JmxTransformer.main(JmxTransformer.java:138)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class com.googlecode.jmxtrans.model.output.InfluxDbWriterFactory] value failed (java.lang.IllegalArgumentExcep
tion): The username may not be null or empty.
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.googlecode.jmxtrans.model.JmxProcess["servers"]->java.util.ArrayList[0]->com.googlecode.jmxtrans.model.Server["queries"]->java.util.Arr
ayList[0]->com.googlecode.jmxtrans.model.Query["outputWriters"]->java.util.ArrayList[0])
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:262)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:445)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:464)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:258)
        at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:135)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:444)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1123)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:298)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:168)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:135)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:120)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:91)
        at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:142)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:279)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:465)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:380)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1123)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:298)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:277)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:465)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:380)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1123)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:298)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:277)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3779)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2050)
        at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2547)
        at com.googlecode.jmxtrans.util.JsonUtils.parseProcess(JsonUtils.java:54)
        at com.googlecode.jmxtrans.ConfigurationParser.parseServers(ConfigurationParser.java:55)
        ... 5 more
Caused by: java.lang.IllegalArgumentException: The username may not be null or empty.
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
        at org.influxdb.InfluxDBFactory.connect(InfluxDBFactory.java:33)
        at com.googlecode.jmxtrans.model.output.InfluxDbWriterFactory.<init>(InfluxDbWriterFactory.java:100)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:114)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:256)
        ... 44 more

```

**Comment by gehel** [comment]
The message tells you "The username may not be null or empty". You should probably try to configure a username and password to your output writer...

I know next to nothing about InfluxDB. It may be that InfluxDB itself allow anonymous connections, but the jmxtrans output writer does not have a way to configure an anonymous connection. If that is the case, you should probably open a request for new feature (and hope someone has time to work on it), or send a patch.

**Comment by gehel** [comment]
As always, documentation is probably lagging behind, but you can have a look at [the code](https://github.com/jmxtrans/jmxtrans/blob/master/jmxtrans-output/jmxtrans-output-influxdb/src/main/java/com/googlecode/jmxtrans/model/output/InfluxDbWriterFactory.java#L75-L86) to see what parameters are available on `InfluxDbWriterFactory`.

**Comment by veerareddyganta** [comment]
I did not configure any user during influx db.  I used json file with out username field, and it gave me the same error.   I will try to setup a user for influx db and test with it.

**Comment by veerareddyganta** [comment]
I am seeing the following in the logs though I am sending username in the json request.

`[17 Nov 2016 18:06:56] [main] 166    DEBUG (com.googlecode.jmxtrans.model.output.InfluxDbWriterFactory:98) - Connecting to url: http://10.10.90.54:8086/ as: username: null
`

```
{
  "servers" : [ {
    "port" : "8999",
    "host" : "10.10.90.54",
    "username" : "admin",
    "password" : "admin",
    "queries" : [ {
      "obj" : "java.lang:type=Memory",
      "attr" : [ "HeapMemoryUsage", "NonHeapMemoryUsage" ],
      "resultAlias":"jvmMemory",
      "outputWriters" : [ {
        "@class" : "com.googlecode.jmxtrans.model.output.InfluxDbWriterFactory",
        "url" : "http://10.10.90.54:8086/",
        "database" : "jmxDB"
      } ]
    } ]
  } ]
}
```

**Comment by gehel** [comment]
The configuration extract above show that you are configuring a username / password onthe `Server`, which is used to connect via JMX to the application being monitored. You don't seem to have configured any credentials on the `InfluxDbWriterFactory`.

**Comment by veerareddyganta** [comment]
Thanks for pointing out the problem.  I am able to successfully start jmxtrans process using the following json.

```
{
  "servers" : [ {
    "port" : "8999",
    "host" : "10.19.93.54",
    "queries" : [ {
      "obj" : "java.lang:type=Memory",
      "attr" : [ "HeapMemoryUsage", "NonHeapMemoryUsage" ],
      "resultAlias":"jvmMemory",
      "outputWriters" : [ {
        "@class" : "com.googlecode.jmxtrans.model.output.InfluxDbWriterFactory",
        "url" : "http://10.19.93.54:8086/",
        **"username" : "admin",
        "password" : "admin",**
        "database" : "jmxDB"
      } ]
    } ]
  } ]
}

```

**Comment by gehel** [comment]
Glad to see it works! Feel free to update the [documentation](https://github.com/jmxtrans/jmxtrans/wiki/InfluxDBWriter).

**Comment by veerareddyganta** [comment]
Done.  I have just added username and password in the example and also added the following in 'Output Writer attributes' section.

username - The username for InfluxDB
password - The password for InfluxDB

**Comment by veerareddyganta** [comment]
Please suggest how to open a request for new feature (jmxtrans output writer provides a way to configure an anonymous connection)

**Comment by gehel** [comment]
Just open an issue describing what new feature you want.
