### ISSUE TITLE
NaN values cause NumberFormatException in CPrecisionValueTransformer

### ISSUE THREAD

**Issue by itzg** [jmxtrans/jmxtrans#529]
When a JMX floating point value is queried to be NaN, the record fails to get output to the statsd writer due to a NumberFormatException, shown below. 

I have reproduced the issue with [this unit test](https://github.com/itzg/jmxtrans/commit/2b69e97bfcae4c90a61b3cdf302487805c2087e0#diff-04f860c1b01da97354617bbb40076ce6R72).

If there's no objections I can proceed with a PR to return null in that scenario.

The NumberFormatException exception trace:
```
java.lang.NumberFormatException
        at java.math.BigDecimal.<init>(BigDecimal.java:494)
        at java.math.BigDecimal.<init>(BigDecimal.java:383)
        at java.math.BigDecimal.<init>(BigDecimal.java:806)
        at com.googlecode.jmxtrans.model.results.CPrecisionValueTransformer.apply(CPrecisionValueTransformer.java:38)
        at com.googlecode.jmxtrans.model.output.StatsDWriter2.computeActualValue(StatsDWriter2.java:97)
        at com.googlecode.jmxtrans.model.output.StatsDWriter2.write(StatsDWriter2.java:85)
        at com.googlecode.jmxtrans.model.output.support.WriterPoolOutputWriter.doWrite(WriterPoolOutputWriter.java:57)
        at com.googlecode.jmxtrans.jmx.ResultProcessor$1.run(ResultProcessor.java:58)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by gehel** [comment]
A PR would be great! Thanks!
