### ISSUE TITLE
queryProcessorExecutor to have not more than two ProcessQueryThread tasks for one server+query

### ISSUE THREAD

**Issue by gowa** [jmxtrans/jmxtrans#565]
Hi!
I'm observing logs flooded with error messages like this:
Could not submit query {}. You could try to size the 'queryProcessorExecutor' to a larger size.
(JmxUtils#processServer)
queryProcessorExecutor has got a limit of 100000 tasks and it seems that they cannot be executed before next ServerJob.execute is triggered.

This also results in a very small chance for scheduling a full list of ProcessQueryThread tasks for each server when some server is responding slower than others. The executor queue is full of slow tasks and prevents others to be enqueued.

Isn't it better to have something that prevents having more than, say, two similar ProcessQueryThread tasks in queryProcessorExecutor?

I'm far from producing a good code but this fix seems to solve my problem:
[jmx.zip](https://github.com/jmxtrans/jmxtrans/files/954533/jmx.zip)

**Comment by gehel** [comment]
Thanks for sending this fix! Any chance you could send it as a pull request and not an attached .zip file? It would be much easier to read and process!

In the end, the right solution to this would be to add circuit breakers on both the JMX connections and the output writers. I need to find some time to actually implement that (you are of course welcomed to send a PR!).

**Comment by gehel** [comment]
@gowa: could you have a look at #566 and see if it resolves your issue?

**Comment by gowa** [comment]
@gehel , thank you your response and commit. I will make a fresh build with your commit and come back with a report after hours of monitoring.
sorry for not providing a push request - never did that before, and the quality of my contibution would be poor...

**Comment by gowa** [comment]
@gehel , unfortunately if I simply replace the version 265 all jar by jar with CircuitBreaker commit then jmxtrans stops working for me completely.

my logs are full of the following messages and no metrics are submitted to Graphite at all.

```
[26 Apr 2017 15:36:27] [jmxtrans-query-0] 148969 ERROR (com.googlecode.jmxtrans.jmx.ProcessQueryThread:57) - Error executing query Query(
    objectName=com.bea:ServerRuntime=clust4,Name=/*hidden*/,Type=JDBCConnectionPoolRuntime
  , keys=[]
  , attr=[ActiveConnectionsCurrentCount, ActiveConnectionsHighCount, ConnectionsTotalCount, CurrCapacity, FailuresToReconnectCount, NumUnavailable, NumAvailable, WaitingForConnectionHighCount, WaitingForConnectionCurrentCount]
  , typeNames=[]
  , resultAlias=/*hidden*/
  , useObjDomainAsKey=false
  , allowDottedKeys=false
  , useAllTypeNames=false
  , outputWriterInstances=[
      GraphiteWriter(
        pool=org.apache.commons.pool.impl.GenericKeyedObjectPool@8add7b
      , rootPrefix=/*hidden*/
      , address=localhost/127.0.0.1:22003
      , onlyOnceLogger=com.googlecode.jmxtrans.util.OnlyOnceLogger@318a7d)]
  ) on server Server(
    pid=null
  , host=/*hidden*/
  , port=/*hidden*/
  , url=service:jmx:iiop:///*hidden*//jndi/weblogic.management.mbeanservers.runtime, cronExpression=null, numQueryThreads=1
  )
net.jodah.failsafe.CircuitBreakerOpenException
	at net.jodah.failsafe.SyncFailsafe.call(SyncFailsafe.java:136)
	at net.jodah.failsafe.SyncFailsafe.get(SyncFailsafe.java:56)
	at com.googlecode.jmxtrans.model.Server.execute(Server.java:289)
	at com.googlecode.jmxtrans.jmx.ProcessQueryThread.run(ProcessQueryThread.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

This very likely clashes with another issue I have (but this one does not prevent jmxtrans to work correctly with the version 265 all jar):

```
[26 Apr 2017 15:32:32] [jmxtrans-query-3] 0      ERROR (com.googlecode.jmxtrans.jmx.ProcessQueryThread:57) - Error executing query Query(
    objectName=com.bea:ServerRuntime=clust4,Name=/*hidden*/,Type=JDBCConnectionPoolRuntime
  , keys=[]
  , attr=[ActiveConnectionsCurrentCount, ActiveConnectionsHighCount, ConnectionsTotalCount, CurrCapacity, FailuresToReconnectCount, NumUnavailable, NumAvailable, WaitingForConnectionHighCount, WaitingForConnectionCurrentCount]
  , typeNames=[]
  , resultAlias=/*hidden*/
  , useObjDomainAsKey=false
  , allowDottedKeys=false
  , useAllTypeNames=false
  , outputWriterInstances=[
      GraphiteWriter(
        pool=org.apache.commons.pool.impl.GenericKeyedObjectPool@8add7b
      , rootPrefix=/*hidden*/
      , address=localhost/127.0.0.1:22003
      , onlyOnceLogger=com.googlecode.jmxtrans.util.OnlyOnceLogger@318a7d)]
  ) on server Server(
    pid=null
  , host=/*hidden*/
  , port=/*hidden*/
  , url=service:jmx:iiop:///*hidden*//jndi/weblogic.management.mbeanservers.runtime, cronExpression=null, numQueryThreads=1
  ) 
java.lang.IllegalStateException: Cannot register two instances of WorkContextAccessController
	at weblogic.workarea.spi.WorkContextAccessController.<init>(WorkContextAccessController.java:24)
	at weblogic.workarea.spi.WorkContextAccessController$1.<init>(WorkContextAccessController.java:65)
	at weblogic.workarea.spi.WorkContextAccessController.getAccessController(WorkContextAccessController.java:65)
	at weblogic.workarea.spi.WorkContextAccessController.isAccessAllowed(WorkContextAccessController.java:38)
	at weblogic.workarea.WorkContextLocalMap.put(WorkContextLocalMap.java:50)
	at weblogic.workarea.WorkContextLocalMap.put(WorkContextLocalMap.java:62)
	at weblogic.workarea.WorkContextMapImpl.put(WorkContextMapImpl.java:52)
	at weblogic.management.context.JMXContextHelper$DefaultJMXContextAccessImpl.putJMXContext(JMXContextHelper.java:89)
	at weblogic.management.context.JMXContextHelper.putJMXContext(JMXContextHelper.java:36)
	at weblogic.management.remote.common.RMIConnectionWrapper.initializeJMXContext(ClientProviderBase.java:1019)
	at weblogic.management.remote.common.RMIConnectionWrapper.getMBeanInfo(ClientProviderBase.java:1029)
	at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.getMBeanInfo(Unknown Source)
	at com.googlecode.jmxtrans.model.Query.fetchResults(Query.java:212)
	at com.googlecode.jmxtrans.model.Server.execute(Server.java:268)
	at com.googlecode.jmxtrans.jmx.ProcessQueryThread.run(ProcessQueryThread.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

Does this mean that the Circuit Breaker becomes Open with the first exception and this state remains unchanged forever?

**Comment by gehel** [comment]
The circuit breaker should go to [half-open and try again connecting after 1 minute ](https://github.com/jmxtrans/jmxtrans/pull/566/files#diff-a667420575437c9cd9c5c0dc5e74d16eR268) (but honestly, I don't have muc experience with this circuit breaker implementation, so I might have done something stupid). I might want to be a little less aggressive with that circuit breaker. At the moment, it opens if there are more than 2 errors on the last 4 attempts. I'll try to relax that a bit. Still, that error with weblogic probably needs fixing as well...

**Comment by gehel** [comment]
@gowa I updated the pull request, could you try again? If you could upload the full log somewhere, I'd be interested in having a look...

**Comment by gowa** [comment]
@gehel , Ok (but I'm sorry not able to do this within next 2-3 hours...).
One thing I realized from reviewing the code, if I'm not mistaken, "numQueryThreads" JSON property is not being used and does not affect threading and JMX connection pooling. This mean it does not allow to limit JMX connections to each server and that ServerJob's interfere with each other in one executorServer. This does not seem to me a good approach. Did you have "numQueryThreads" feature working ever? Or I simply did not understand the code.... or for some reasons you refused to support it.

Thanks

PS. I only heard about CircuitBreaker from "Release It!" book... never implemented it properly.

**Comment by gehel** [comment]
The numQueryThreads is a left over from an old refactoring. I should clean that up and log a warning if someone tries to use it. At that point, threads were allocated for each server, instead of having a pool of thread and a limit on the number of connections. The current approach (a pool of connections per server, with a limit and a shared pool of threads) seems better, except that it is still not as robust as we could wish...

**Comment by gehel** [comment]
Take your time for testing, I'm probably not going to have time to dig further into this before next Monday...

**Comment by gowa** [comment]
ok.)
> The current approach (a pool of connections per server, with a limit and a shared pool of threads)
The thing is I was not able to understand how number of connections is limited for each server... And if Servers do have their own connection pools with limit it is not clear how workers in shared pool of threads can work with those connection pools without waiter/blockers.

Thanks a lot!
This tool helps me very very much!

**Comment by gowa** [comment]
@gehel,
I've been testing your new pull request.
In my opinion, using CircuitBreaker does not allow to fix the problem with overflowing queryProcessorExecutor: if JMX polling tasks are slow and do not finish until next task submission then queryProcessorExecutor will be full in the end anyway.

I've found the following problems:
1) Problem with the old GraphiteWriter (the problem does exist in circuitbreaker version and does not exist in master):
`[02 May 2017 10:35:18] [jmxtrans-result-0] 7790   WARN  (com.googlecode.jmxtrans.jmx.ResultProcessor$1:60) - Could not write results [] of query Query(objectName=com.bea:ServerRuntime=/*hidden*/,Name=/*hidden*/!/*hidden*/,Type=JMSDestinationRuntime,JMSServerRuntime=/*hidden*/, keys=[], attr=[MessagesCurrentCount, MessagesHighCount, MessagesPendingCount, MessagesReceivedCount], typeNames=[], resultAlias=/*hidden*/, useObjDomainAsKey=false, allowDottedKeys=false, useAllTypeNames=false, outputWriterInstances=[GraphiteWriter(pool=org.apache.commons.pool.impl.GenericKeyedObjectPool@1dd638a, rootPrefix=/*hidden*/./*hidden*/, address=localhost/127.0.0.1:22003, onlyOnceLogger=com.googlecode.jmxtrans.util.OnlyOnceLogger@c40605)]) to output writer GraphiteWriter(pool=org.apache.commons.pool.impl.GenericKeyedObjectPool@1dd638a, rootPrefix=/*hidden*/./*hidden*/, address=localhost/127.0.0.1:22003, onlyOnceLogger=com.googlecode.jmxtrans.util.OnlyOnceLogger@c40605)
java.lang.NullPointerException
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220)
	at com.googlecode.jmxtrans.model.output.GraphiteWriter.internalWrite(GraphiteWriter.java:116)
	at com.googlecode.jmxtrans.model.output.BaseOutputWriter.doWrite(BaseOutputWriter.java:157)
	at com.googlecode.jmxtrans.model.CircuitBreakerOutputWriter$2.run(CircuitBreakerOutputWriter.java:76)
	at net.jodah.failsafe.Functions$10.call(Functions.java:252)
	at net.jodah.failsafe.SyncFailsafe.call(SyncFailsafe.java:145)
	at net.jodah.failsafe.SyncFailsafe.run(SyncFailsafe.java:81)
	at com.googlecode.jmxtrans.model.CircuitBreakerOutputWriter.doWrite(CircuitBreakerOutputWriter.java:73)
	at com.googlecode.jmxtrans.jmx.ResultProcessor$1.run(ResultProcessor.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
`

2. I've replace GraphiteWriter by GraphiteWriterFactory as advised in code and face the following (a number of time after jmxtrans started - don't know whether it is ok and is recoverable - JFYI):
`[02 мая 2017 09:05:24] [Stormpot-pool-3-thread-108] 609    ERROR (com.googlecode.jmxtrans.model.output.support.pool.RetryingAllocator$1:77) - Error allocating slot
java.net.SocketTimeoutException: connect timed out
        at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at com.googlecode.jmxtrans.model.output.support.pool.SocketAllocator.allocate(SocketAllocator.java:61)
        at com.googlecode.jmxtrans.model.output.support.pool.SocketAllocator.allocate(SocketAllocator.java:37)
        at com.googlecode.jmxtrans.model.output.support.pool.RetryingAllocator$2.call(RetryingAllocator.java:89)
        at com.googlecode.jmxtrans.model.output.support.pool.RetryingAllocator$2.call(RetryingAllocator.java:86)
        at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(AttemptTimeLimiters.java:78)
        at com.github.rholder.retry.Retryer.call(Retryer.java:160)
        at com.googlecode.jmxtrans.model.output.support.pool.RetryingAllocator.allocate(RetryingAllocator.java:86)
        at stormpot.ReallocatingAdaptor.allocate(ReallocatingAdaptor.java:37)
        at stormpot.BAllocThread.alloc(BAllocThread.java:225)
        at stormpot.BAllocThread.increaseSizeByAllocating(BAllocThread.java:131)
        at stormpot.BAllocThread.replenishPool(BAllocThread.java:106)
        at stormpot.BAllocThread.continuouslyReplenishPool(BAllocThread.java:88)
        at stormpot.BAllocThread.run(BAllocThread.java:80)
        at java.lang.Thread.run(Unknown Source)`

I decided to set com.googlecode.jmxtrans.model.output.support.TcpOutputWriterBuilder#socketTimeoutMillis to 10 seconds.

3. Your new version of circuitbreaker does work but for just a few seconds after launch. In logs the following appears:
`INFO  (com.googlecode.jmxtrans.model.Server$1:282) - Circuit breaker opened for server Server(...`

and then logs are full of:
`[02 May 2017 09:25:23] [jmxtrans-query-4] 3634   ERROR (com.googlecode.jmxtrans.jmx.ProcessQueryThread:57) - Error executing query Query(objectName=com.bea:ServerRuntime=/*hidden*/,Name=Default[http],Type=ServerChannelRuntime, keys=[], attr=[AcceptCount, BytesReceivedCount, BytesSentCount, ConnectionsCount, MessagesReceivedCount, MessagesSentCount], typeNames=[], resultAlias=http, useObjDomainAsKey=false, allowDottedKeys=false, useAllTypeNames=false, outputWriterInstances=[com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter@11ad2a4]) on server Server(pid=null, host=/*hidden*/, port=6841, url=service:jmx:iiop:///*hidden*/:6841/jndi/weblogic.management.mbeanservers.runtime, cronExpression=null, numQueryThreads=1)
net.jodah.failsafe.CircuitBreakerOpenException
	at net.jodah.failsafe.SyncFailsafe.call(SyncFailsafe.java:136)
	at net.jodah.failsafe.SyncFailsafe.get(SyncFailsafe.java:56)
	at com.googlecode.jmxtrans.model.Server.execute(Server.java:289)
	at com.googlecode.jmxtrans.jmx.ProcessQueryThread.run(ProcessQueryThread.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
`

I tried to fix this by adjusting CircuitBreaker timeout in Server class constructor:
`.withTimeout(5000, MILLISECONDS)`

This helped. My assumption of CircuitBreaker becoming open due to slow server reponses has been confirmed. But as a result this did not solve the problem with queryProcessorExecutor - the work queue started to grow and reached 100000.

All above lead me to the following conclusions:
1. CircuitBreaker itself does not prevent queryProcessorExecutor overflowing: even if the server is responding very fast the size of the configured set of metrics to be collected can be so large that even a wisely chosen interval of polling will be less than the time required to complete of all previous iteration tasks.

2. It seems that CircuitBreaker timeout should be configurable because we cannot assume that each server is capable to respond within 250 millis.

**Comment by gehel** [comment]
Thanks for the testing!
A few comments:

> CircuitBreaker itself does not prevent queryProcessorExecutor overflowing: even if the server is responding very fast the size of the configured set of metrics to be collected can be so large that even a wisely chosen interval of polling will be less than the time required to complete of all previous iteration tasks.

Yes, that's true. If you have very slow servers, you might need to adjust the size of the thread pools (`--result-processor-executor-pool-size` and `--result-processor-executor-work-queue-capacity`). But in the end, if the number of metrics to collect increases above the possible throughput of jmxtrans, you are going to run into issues (but that limit *should* be high enough).

> It seems that CircuitBreaker timeout should be configurable because we cannot assume that each server is capable to respond within 250 millis.

Yes, it definitely should be configurable. I'll have a look into it.

5 seconds to collect metrics over JMX seems like a really long time. I'll also add some code to log the time spend in metric collection to get a better view of what is going on. 

I also realized that the [JMX pool is not bounded](https://github.com/jmxtrans/jmxtrans/blob/master/jmxtrans-core/src/main/java/com/googlecode/jmxtrans/guice/JmxTransModule.java#L148-L168), which is a mistake. So we might be in a situation where JMX queries are piling up on a server and making it slow down, which would make the situation worse.

Side note, I need to take some time to replace the stormpot connection pool (used in new output writers) by commons-pool. This will also change the situation a bit.
