### ISSUE TITLE
Support for conenct to "outputWriters.connectionUrl" via Proxy

### ISSUE THREAD

**Issue by sivapms** [jmxtrans/jmxtrans#577]
Hello,

I was trying use JMXTrans for collecting JVM stats and push it to elastic search endpoint. 
Unfortunately I cannot reach the endpoint directly but only via a proxy. I couldn't find an option to provide proxy url for connecting to connectionUrl

[<Date Time>] [WrapperSimpleAppMain] 6584   ERROR (com.googlecode.jmxtrans.JmxTransformer:190) - Failed to create elastic mapping.
com.googlecode.jmxtrans.exceptions.LifecycleException: Failed to create elastic mapping.
        at com.googlecode.jmxtrans.model.output.elastic.ElasticWriter.start(ElasticWriter.java:178)
        at com.googlecode.jmxtrans.JmxTransformer.processServersIntoJobs(JmxTransformer.java:369)
        at com.googlecode.jmxtrans.JmxTransformer.startupSystem(JmxTransformer.java:325)
        at com.googlecode.jmxtrans.JmxTransformer.start(JmxTransformer.java:187)
        at com.googlecode.jmxtrans.JmxTransformer.doMain(JmxTransformer.java:157)
        at com.googlecode.jmxtrans.JmxTransformer.main(JmxTransformer.java:138)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to <elasticsearch_url>:80 [<elasticsearch_url>, <elasticsearch_url>] failed: connect timed out
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:150)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
        at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:47)
        at com.googlecode.jmxtrans.model.output.elastic.ElasticWriter.createMappingIfNeeded(ElasticWriter.java:149)
        at com.googlecode.jmxtrans.model.output.elastic.ElasticWriter.start(ElasticWriter.java:176)
        ... 11 more
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)

JestClient creation doesn't have option to provide proxy for connecting to connectionUrl. 
Can we have another method that creates the JestClient with proxy object set? 

	private JestClient createJestClient(String connectionUrl) {
		log.info("Create a jest elastic search client for connection url [{}]", connectionUrl);
		JestClientFactory factory = new JestClientFactory();
		factory.setHttpClientConfig(
				new HttpClientConfig.Builder(connectionUrl)
						.multiThreaded(true)
						.build());
		return factory.getObject();
}

Thanks

**Comment by gehel** [comment]
Thanks! That sounds like a good feature to add. Any chance that you could send a pull request?

**Comment by jbrunsek** [comment]
👍 I'm looking for something similar. This would be a great addition to see
