### ISSUE TITLE
jmxtrans connecting issues to a remote machine

### ISSUE THREAD

**Issue by akkumar** [jmxtrans/jmxtrans#58]
I had installed jmxtrans locally. I am trying to connect to the same. 

The url published by jmxtrans is as below: 

url=service:jmx:rmi:///jndi/rmi://10.148.1.3:1105/jmxrmi

On the server side (where jmx is running): 

  $ ps -ef | grep solr
root     15200     1  0 Feb07 ?        00:02:02 /usr/share/jdk7/bin/java -Djava.util.logging.config.file=/myarg/search-service/releases/current//conf/logging.properties -server -Xmx4096m -Xms4096m -Dsolr.solr.home=/myarg/search-service/releases/current/solrhome/ -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=1105 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=10.148.1.3 -Djava.endorsed.dirs=/opt/software/tomcat7/endorsed -classpath /opt/software/tomcat7/bin/bootstrap.jar:/myarg/search-service/releases/current//bin/tomcat-juli.jar -Dcatalina.base=/myarg/search-service/releases/current/ -Dcatalina.home=/opt/software/tomcat7 -Djava.io.tmpdir=/myarg/search-service/releases/current//temp org.apache.catalina.startup.Bootstrap start
504      23407 23384  0 00:05 pts/0    00:00:00 grep solr

telnet to the remote port works fine. ( telnet 10.148.1.3 1105 ) . 

It fails with the following error: 

 [ServerScheduler_Worker-8] 367810285 ERROR (com.googlecode.jmxtrans.jobs.ServerJob:39) - Error
java.rmi.ConnectException: Connection refused to host: 10.148.1.3; nested exception is: 
       java.net.ConnectException: Conne
       ction timed out
       at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:601)
       at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:198)
       at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:184)
       at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:110)
       at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(Unknown Source)
       at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2327)
       at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:277)
       at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:248)
       at com.googlecode.jmxtrans.util.JmxUtils.getServerConnection(JmxUtils.java:351)
       at com.googlecode.jmxtrans.util.JmxConnectionFactory.makeObject(JmxConnectionFactory.java:31)
       at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1212)
       at com.googlecode.jmxtrans.jobs.ServerJob.execute(ServerJob.java:36)
       at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
       at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549)
Caused by: java.net.ConnectException: Connection timed out
       at java.net.PlainSocketImpl.socketConnect(Native Method)
       at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
       at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
       at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
       at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
       at java.net.Socket.connect(Socket.java:529)

Not sure what the issue is, since telnet seems to connect fine. ( Opened up firewall for TCP / 1105 for communication as well).  Anything else that we are missing here. Thanks !

**Comment by kdoubner** [comment]
You can specify which port to use 
`-Dcom.sun.management.jmxremote.rmi.port=9998` 
check https://stackoverflow.com/a/40666287/2235381
