### ISSUE TITLE
Could not write results

### ISSUE THREAD

**Issue by terry19850829** [jmxtrans/jmxtrans#584]
Use jmxtrans monitor kafka
influxDB as storage ,influxdb version is 1.2.0
jmxtrans 265

```
[30 六月 2017 17:05:52] [jmxtrans-result-0] 20047  WARN  (com.googlecode.jmxtrans.jmx.ResultProcessor$1:60) - Could not write results [Result(attributeName=Connected, className=io.debezium.connector.mysql.BinlogReaderMetrics, objDomain=debezium.mysql, typeName=type=connector-metrics,context=binlog,server=binlog.alpha-001, values={Connected=true}, epoch=1498813542241, keyAlias=null), Result(attributeName=BinlogFilename, className=io.debezium.connector.mysql.BinlogReaderMetrics, objDomain=debezium.mysql, typeName=type=connector-metrics,context=binlog,server=binlog.alpha-001, values={BinlogFilename=mysql-binlog.000005}, epoch=1498813542241, keyAlias=null), Result(attributeName=BinlogPosition, className=io.debezium.connector.mysql.BinlogReaderMetrics, objDomain=debezium.mysql, typeName=type=connector-metrics,context=binlog,server=binlog.alpha-001, values={BinlogPosition=52797758}, epoch=1498813542241, keyAlias=null), Result(attributeName=GtidSet, className=io.debezium.connector.mysql.BinlogReaderMetrics, objDomain=debezium.mysql, typeName=type=connector-metrics,context=binlog,server=binlog.alpha-001, values={GtidSet=2934dea9-5b3b-11e7-ab17-74d4351a72fa:1-121717}, epoch=1498813542241, keyAlias=null), Result(attributeName=SecondsBehindMaster, className=io.debezium.connector.mysql.BinlogReaderMetrics, objDomain=debezium.mysql, typeName=type=connector-metrics,context=binlog,server=binlog.alpha-001, values={SecondsBehindMaster=69128}, epoch=1498813542241, keyAlias=null), Result(attributeName=TotalNumberOfEventsSeen, className=io.debezium.connector.mysql.BinlogReaderMetrics, objDomain=debezium.mysql, typeName=type=connector-metrics,context=binlog,server=binlog.alpha-001, values={TotalNumberOfEventsSeen=608410}, epoch=1498813542241, keyAlias=null), Result(attributeName=NumberOfSkippedEvents, className=io.debezium.connector.mysql.BinlogReaderMetrics, objDomain=debezium.mysql, typeName=type=connector-metrics,context=binlog,server=binlog.alpha-001, values={NumberOfSkippedEvents=0}, epoch=1498813542241, keyAlias=null), Result(attributeName=NumberOfDisconnects, className=io.debezium.connector.mysql.BinlogReaderMetrics, objDomain=debezium.mysql, typeName=type=connector-metrics,context=binlog,server=binlog.alpha-001, values={NumberOfDisconnects=0}, epoch=1498813542241, keyAlias=null), Result(attributeName=SecondsSinceLastEvent, className=io.debezium.connector.mysql.BinlogReaderMetrics, objDomain=debezium.mysql, typeName=type=connector-metrics,context=binlog,server=binlog.alpha-001, values={SecondsSinceLastEvent=94718}, epoch=1498813542241, keyAlias=null), Result(attributeName=LastEvent, className=io.debezium.connector.mysql.BinlogReaderMetrics, objDomain=debezium.mysql, typeName=type=connector-metrics,context=binlog,server=binlog.alpha-001, values={LastEvent=XID/1498649691000 from server 1}, epoch=1498813542241, keyAlias=null)] of query Query(objectName=debezium.mysql:type=connector-metrics,context=binlog,server=binlog.alpha-001, keys=[], attr=[], typeNames=[], resultAlias=null, useObjDomainAsKey=false, allowDottedKeys=false, useAllTypeNames=false, outputWriterInstances=[com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter@496c3cc5]) to output writer com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter@496c3cc5
java.lang.RuntimeException: java.net.SocketTimeoutException: timeout
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at org.influxdb.impl.InfluxDBImpl.ping(InfluxDBImpl.java:140)
	at org.influxdb.impl.InfluxDBImpl.version(InfluxDBImpl.java:146)
	at org.influxdb.impl.InfluxDBImpl.createDatabase(InfluxDBImpl.java:227)
	at com.googlecode.jmxtrans.model.output.InfluxDbWriter.doWrite(InfluxDbWriter.java:151)
	at com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter.doWrite(ResultTransformerOutputWriter.java:52)
	at com.googlecode.jmxtrans.jmx.ResultProcessor$1.run(ResultProcessor.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: timeout
	at okio.Okio$3.newTimeoutException(Okio.java:210)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:288)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:242)
	at okio.RealBufferedSource.read(RealBufferedSource.java:45)
	at okhttp3.internal.http.Http1xStream$UnknownLengthSource.read(Http1xStream.java:472)
	at okio.RealBufferedSource.readAll(RealBufferedSource.java:162)
	at retrofit2.Utils.buffer(Utils.java:303)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:198)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
	at org.influxdb.impl.InfluxDBImpl.ping(InfluxDBImpl.java:126)
	... 10 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:138)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:238)
	... 17 more
```

**Comment by terry19850829** [comment]
just because my proxy ...
