### ISSUE TITLE
NagiosWriter. Error parsing json. NullPointerException

### ISSUE THREAD

**Issue by WinterUnicorn** [jmxtrans/jmxtrans#610]
Hello! We are trying to connect jmxtrans with our local nagios server but we cannot because of parsing issue. We use next json-file (based on example from wiki):  
{
  "servers" : [ {
    "host" : "myhost",
    "port" : "7005",
    "queries" : [ {
      "obj" : "java.lang:type=Memory",
      "attr" : [ "HeapMemoryUsage", "NonHeapMemoryUsage" ],
      "outputWriters" :[{
        "@class" : "com.googlecode.jmxtrans.model.output.NagiosWriter",
        "settings" : {
          "booleanAsNumber":"false",
          "debug":"true", 
          "typeNames" : [ "name" ],
          "outputFile": "/tmp/denis_jmx",
          "nagiosHost": "myhost.hst",
          "prefix": "Pre ",
          "posfix": " Pos",
          "filters": ["HeapMemoryUsage_used", "NonHeapMemoryUsage_max"],
          "thresholds": ["@1000000000:3000000000,", ""]
        }
      } ]
    } ]
  } ]
}  

and after start we have next error. 
Could you help us to resolve a root cause of problem?

[29 Sep 2017 15:04:52] [main] 0      INFO  (com.googlecode.jmxtrans.JmxTransformer:181) - Starting Jmxtrans on : etc/jmxtrans/json
[29 Sep 2017 15:04:52] [main] 0      INFO  (com.googlecode.jmxtrans.JmxTransformer:181) - Starting Jmxtrans on : etc/jmxtrans/json
[29 Sep 2017 15:04:52] [main] 190    WARN  (com.googlecode.jmxtrans.model.output.BaseOutputWriter:92) - Using 'settings' is deprecated, please pass attributes directly to the OutputWriter.
[29 Sep 2017 15:04:52] [main] 190    WARN  (com.googlecode.jmxtrans.model.output.BaseOutputWriter:92) - Using 'settings' is deprecated, please pass attributes directly to the OutputWriter.
[29 Sep 2017 15:04:52] [main] 194    ERROR (com.googlecode.jmxtrans.JmxTransformer:190) - Error parsing json: etc/jmxtrans/json/test.json
com.googlecode.jmxtrans.exceptions.LifecycleException: Error parsing json: etc/jmxtrans/json/test.json
	at com.googlecode.jmxtrans.ConfigurationParser.parseServers(ConfigurationParser.java:62)
	at com.googlecode.jmxtrans.JmxTransformer.processFilesIntoServers(JmxTransformer.java:354)
	at com.googlecode.jmxtrans.JmxTransformer.startupSystem(JmxTransformer.java:322)
	at com.googlecode.jmxtrans.JmxTransformer.start(JmxTransformer.java:187)
	at com.googlecode.jmxtrans.JmxTransformer.doMain(JmxTransformer.java:157)
	at com.googlecode.jmxtrans.JmxTransformer.main(JmxTransformer.java:138)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.googlecode.jmxtrans.model.output.NagiosWriter, problem: null
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.googlecode.jmxtrans.model.JmxProcess["servers"]->java.util.ArrayList[0]->com.googlecode.jmxtrans.model.Server["queries"]->java.util.ArrayList[0]->com.googlecode.jmxtrans.model.Query["outputWriters"]->java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:277)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1441)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:476)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:495)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:276)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:228)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:471)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1191)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:183)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:150)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:129)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:209)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:289)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:400)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1191)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:287)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:400)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1191)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:287)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:104)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3786)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2115)
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2612)
	at com.googlecode.jmxtrans.util.ProcessConfigUtils.parseProcess(ProcessConfigUtils.java:62)
	at com.googlecode.jmxtrans.ConfigurationParser.parseServers(ConfigurationParser.java:55)
	... 5 more
Caused by: java.lang.NullPointerException
	at com.googlecode.jmxtrans.model.output.NagiosWriter.<init>(NagiosWriter.java:106)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:274)
	... 45 more
[29 Sep 2017 15:04:52] [main] 194    ERROR (com.googlecode.jmxtrans.JmxTransformer:190) - Error parsing json: etc/jmxtrans/json/test.json
com.googlecode.jmxtrans.exceptions.LifecycleException: Error parsing json: etc/jmxtrans/json/test.json
	at com.googlecode.jmxtrans.ConfigurationParser.parseServers(ConfigurationParser.java:62)
	at com.googlecode.jmxtrans.JmxTransformer.processFilesIntoServers(JmxTransformer.java:354)
	at com.googlecode.jmxtrans.JmxTransformer.startupSystem(JmxTransformer.java:322)
	at com.googlecode.jmxtrans.JmxTransformer.start(JmxTransformer.java:187)
	at com.googlecode.jmxtrans.JmxTransformer.doMain(JmxTransformer.java:157)
	at com.googlecode.jmxtrans.JmxTransformer.main(JmxTransformer.java:138)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.googlecode.jmxtrans.model.output.NagiosWriter, problem: null
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.googlecode.jmxtrans.model.JmxProcess["servers"]->java.util.ArrayList[0]->com.googlecode.jmxtrans.model.Server["queries"]->java.util.ArrayList[0]->com.googlecode.jmxtrans.model.Query["outputWriters"]->java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:277)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1441)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:476)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:495)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:276)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:228)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:471)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1191)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:183)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:150)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:129)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:209)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:289)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:400)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1191)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:287)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:400)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1191)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:287)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:104)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3786)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2115)
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2612)
	at com.googlecode.jmxtrans.util.ProcessConfigUtils.parseProcess(ProcessConfigUtils.java:62)
	at com.googlecode.jmxtrans.ConfigurationParser.parseServers(ConfigurationParser.java:55)
	... 5 more
Caused by: java.lang.NullPointerException
	at com.googlecode.jmxtrans.model.output.NagiosWriter.<init>(NagiosWriter.java:106)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:274)
	... 45 more

**Comment by WinterUnicorn** [comment]
The issue is here:

106 		if (filters.size() != thresholds.size()) { 
107 			throw new IllegalStateException("filters and thresholds must have the same size."); 
108 		} 

should be:
this.filters.size() != this.thresholds.size()

Could you fix it?

**Comment by 1000000000** [comment]
@WinterUnicorn could you use code blocks for formatting errors and code in issues in the future. In general it looks better and helps set the code or error apart from the surrounding text but it also prevents any @ mentions from being parsed in the code or error (as mine was in your json code). Text can be formatted into code blocks by adding four spaces to the start of each line of text in the block, by adding a line containing three backticks (`) to the beginning and end of the text, or by selecting the block and clicking the '<>' button on the UI.

Example:
```
Foo
Bar
@WinterUnicorn
```
