### ISSUE TITLE
influxDbwrite trying to create DB

### ISSUE THREAD

**Issue by tanuj83** [jmxtrans/jmxtrans#623]
As per [wiki](https://github.com/jmxtrans/jmxtrans/wiki/InfluxDBWriter), it creates DB if it doesn't exit but here using latest build and even now it is trying to create DB

The issue seems fixed in [#368](https://github.com/jmxtrans/jmxtrans/issues/368) 

`
to output writer com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter@57d2b5e0
org.influxdb.InfluxDBException: {"error":"error authorizing query: influx_user not authorized to execute statement 'CREATE DATABASE my_db', requires admin privilege"}
	at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:511)
	at org.influxdb.impl.InfluxDBImpl.createDatabase(InfluxDBImpl.java:459)
	at com.googlecode.jmxtrans.model.output.InfluxDbWriter.doWrite(InfluxDbWriter.java:160)
	at com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter.doWrite(ResultTransformerOutputWriter.java:53)
	at com.googlecode.jmxtrans.jmx.ResultProcessor$1.run(ResultProcessor.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

Here is config

`
      "outputWriters" : [ {
        "@class" : "com.googlecode.jmxtrans.model.output.InfluxDbWriterFactory",
        "url" : "http://node01.example.com:8086/",
        "username" : "user1",
        "password" : "XXXXXX",
        "database" : "my_db",
        "retentionPolicy" : "my_retention",
        "tags"     : {"application" : "test"}
      } ],
`

**Comment by tanuj83** [comment]
Fixed after using below config

createDatabase" : false,
