### ISSUE TITLE
OpenTSDBWriter NPE

### ISSUE THREAD

**Issue by dijingran** [jmxtrans/jmxtrans#633]
I tried to  use OpenTSDBWriter (version 268) , and i got npe at line 69 of OpenTSDBGenericWriter.
My opentsdb version is 2.3.
Here is my config: 
```javascript
{
  "servers" : [ {
    "port" : "8080",
    "host" : "xxx.xxx.xxx.xxx",
    "queries" : [ {
      "outputWriters" : [ {
        "@class" : "com.googlecode.jmxtrans.model.output.OpenTSDBWriter",
          "port" : 8282,
          "host" : "10.22.240.70",
          "metricNamingExpression" : "a.b",
          "settings" : {},
          "mergeTypeNamesTags" : true,
          "typeNames": [],
          "typeName": "a",
          "tags": {}
      } ],
      "obj" : "java.lang:type=Memory",
      "resultAlias": "heap",
      "attr" : [ "HeapMemoryUsage", "NonHeapMemoryUsage" ]
    }],
    "numQueryThreads" : 2
  } ]
}
```

And this is the exception stack trace:

```
INFO   | jvm 1    | 2017/12/21 15:36:29 | Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.googlecode.jmxtrans.model.output.OpenTSDBWriter, problem: null
INFO   | jvm 1    | 2017/12/21 15:36:29 |  at [Source: N/A; line: -1, column: -1] (through reference chain: com.googlecode.jmxtrans.model.JmxProcess["servers"]->java.util.ArrayList[0]->com.googlecode.jmxtrans.model.Server["queries"]->java.util.ArrayList[0]->com.googlecode.jmxtrans.model.Query["outputWriters"]->java.util.ArrayList[0])
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:277)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1441)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:476)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:495)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:276)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:228)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:138)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:471)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1191)
                                                                                                                                  1782,1        97%
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:400)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1191)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:287)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:104)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3786)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2115)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2612)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at com.googlecode.jmxtrans.util.ProcessConfigUtils.parseProcess(ProcessConfigUtils.java:62)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at com.googlecode.jmxtrans.ConfigurationParser.parseServers(ConfigurationParser.java:55)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       ... 11 more
INFO   | jvm 1    | 2017/12/21 15:36:29 | Caused by: java.lang.NullPointerException
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at com.googlecode.jmxtrans.model.output.OpenTSDBGenericWriter.<init>(OpenTSDBGenericWriter.java:96)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at com.googlecode.jmxtrans.model.output.OpenTSDBWriter.<init>(OpenTSDBWriter.java:75)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
INFO   | jvm 1    | 2017/12/21 15:36:29 |       at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:274)
```

**Comment by dijingran** [comment]
I changed configuration to this , jmxtrans can start up, and 
```javascript
{
  "servers" : [ {
    "port" : "8082",
    "host" : "10.22.244.9",
    "queries" : [ {
      "outputWriters" : [ {
        "@class" : "com.googlecode.jmxtrans.model.output.OpenTSDBWriterFactory",
          "port" : 8282,
          "host" : "10.22.240.70",
          "mergeTypeNamesTags" : true,
          "typeNames": []
      } ],
      "obj" : "java.lang:type=Memory",
      "resultAlias": "heap",
      "attr" : [ "HeapMemoryUsage", "NonHeapMemoryUsage" ]
    }],
    "numQueryThreads" : 2
  } ]
}
```
And the log seems ok, but indeed it didn't write successful.

```
[22 Dec 2017 15:51:18] [jmxtrans-result-4] 885135 TRACE (com.googlecode.jmxtrans.model.output.OpenTSDBWriter2:56) - heap.HeapMemoryUsage 1513929078 
32212254720
[22 Dec 2017 15:51:18] [jmxtrans-result-4] 885135 TRACE (com.googlecode.jmxtrans.model.output.OpenTSDBWriter2:56) - heap.HeapMemoryUsage 1513929078 
32212254720
[22 Dec 2017 15:51:44] [jmxtrans-result-4] 910917 TRACE (com.googlecode.jmxtrans.model.output.OpenTSDBWriter2:56) - heap.HeapMemoryUsage 1513929078 
29527900160
[22 Dec 2017 15:51:44] [jmxtrans-result-4] 910917 TRACE (com.googlecode.jmxtrans.model.output.OpenTSDBWriter2:56) - heap.HeapMemoryUsage 1513929078 29527900160
[22 Dec 2017 15:51:58] [jmxtrans-result-4] 924731 TRACE (com.googlecode.jmxtrans.model.output.OpenTSDBWriter2:56) - heap.HeapMemoryUsage 1513929078 29527900160
[22 Dec 2017 15:51:58] [jmxtrans-result-4] 924731 TRACE (com.googlecode.jmxtrans.model.output.OpenTSDBWriter2:56) - heap.HeapMemoryUsage 1513929078 29527900160
```

**Comment by Carl-Hee** [comment]
I met the same question. Have you already solve the question?

**Comment by dijingran** [comment]
@Carl-Hee  No...

**Comment by dijingran** [comment]
I added two properties, it works now:
"addHostnameTag" : true,     // if not tag specified , put api will not work. 
"flushStrategy" : "always",     //  default is "never" , so the metric wan't sent to opentsdb actually!! 

```javascript
 
{
  "servers" : [ {
    "port" : "8082",
    "host" : "xxx.xxx.xxx.xxx",
    "queries" : [ {
      "outputWriters" : [ {
        "@class" : "com.googlecode.jmxtrans.model.output.OpenTSDBWriterFactory",
          "port" : 8282,
          "host" : "opentsdbhostxxxxxx",
          "mergeTypeNamesTags" : true,
          "addHostnameTag" : true,
          "flushStrategy" : "always",
          "typeNames": []
      } ],
      "obj" : "java.lang:type=Memory",
      "resultAlias": "heap",
      "attr" : [ "HeapMemoryUsage", "NonHeapMemoryUsage" ]
    }],
    "numQueryThreads" : 2
  } ]
}
```

**Comment by Carl-Hee** [comment]
@dijingran I tried your config, but still not work. The error log is like:
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "flushStrategy" (class com.googlecode.
jmxtrans.model.output.OpenTSDBWriter), not marked as ignorable (13 known properties: "port", "booleanAsNumber", "tagName", "addHostnam
eTag", "host", "typeNames", "mergeTypeNamesTags", "metricNamingExpression", "debug", "tags", "pool", "settings", "debugEnabled"])
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.googlecode.jmxtrans.model.JmxProcess["servers"]->java.util.Array
List[0]->com.googlecode.jmxtrans.model.Server["queries"]->java.util.ArrayList[0]->com.googlecode.jmxtrans.model.Query["outputWriters"]
->java.util.ArrayList[0]->com.googlecode.jmxtrans.model.output.OpenTSDBWriter["flushStrategy"])

I use jmxtrans-268

**Comment by Carl-Hee** [comment]
I delete the item flushStrategy, then it works.
Thanks a lot.
