### ISSUE TITLE
output writer com.googlecode.jmxtrans.model.output.support java.net.SocketTimeoutException: timeout

### ISSUE THREAD

**Issue by Yeading** [jmxtrans/jmxtrans#639]
```[01 Feb 2018 17:35:52] [jmxtrans-result-0] 316475 WARN  (com.googlecode.jmxtrans.jmx.ResultProcessor$1:60) - Could not write results [Result(attributeName=Count, className=com.yammer.metrics.reporting.JmxReporter$Meter, objDomain=kafka.server, typeName=type=BrokerTopicMetrics,name=BytesInPerSec, values={Count=2328750452935}, epoch=1517477732826, keyAlias=BytesInPerSec), Result(attributeName=OneMinuteRate, className=com.yammer.metrics.reporting.JmxReporter$Meter, objDomain=kafka.server, typeName=type=BrokerTopicMetrics,name=BytesInPerSec, values={OneMinuteRate=778693.296272109}, epoch=1517477732826, keyAlias=BytesInPerSec)] of query Query(objectName=kafka.server:type=BrokerTopicMetrics,name=BytesInPerSec, keys=[], attr=[Count, OneMinuteRate], typeNames=[], resultAlias=BytesInPerSec, useObjDomainAsKey=false, allowDottedKeys=false, useAllTypeNames=false, outputWriterInstances=[com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter@295c8725]) to output writer com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter@295c8725
java.lang.RuntimeException: java.net.SocketTimeoutException: timeout
        at com.google.common.base.Throwables.propagate(Throwables.java:160)
        at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:270)
        at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:167)
        at com.googlecode.jmxtrans.model.output.InfluxDbWriter.doWrite(InfluxDbWriter.java:174)
        at com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter.doWrite(ResultTransformerOutputWriter.java:52)
        at com.googlecode.jmxtrans.jmx.ResultProcessor$1.run(ResultProcessor.java:58)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: timeout
```

#-------------why does it can't write data to influxdb？
someone can help me about the issue

**Comment by gehel** [comment]
`java.net.SocketTimeoutException: timeout` lets me think that your influxdb is not responding.

**Comment by Yeading** [comment]
yes,you are right

**Comment by gehel** [comment]
Did you find the issue? Should we close this task?

**Comment by Yeading** [comment]
yes.thanks you so much!
