### ISSUE TITLE
NPE when connecting to JVM with PID

### ISSUE THREAD

**Issue by gquintana** [jmxtrans/jmxtrans#642]
```
java.lang.NullPointerException
	at java.management/javax.management.remote.JMXServiceURL.<init>(JMXServiceURL.java:148)
	at com.googlecode.jmxtrans.model.Server.getServerConnection(Server.java:341)
	at com.googlecode.jmxtrans.connections.MBeanServerConnectionFactory.makeObject(MBeanServerConnectionFactory.java:38)
	at com.googlecode.jmxtrans.connections.MBeanServerConnectionFactory.makeObject(MBeanServerConnectionFactory.java:31)
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220)
	at com.googlecode.jmxtrans.model.Server.execute(Server.java:273)
	at com.googlecode.jmxtrans.jmx.ProcessQueryThread.run(ProcessQueryThread.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
```
Tested on JMXTrans 268

**Comment by gehel** [comment]
Fixed by #643
