### ISSUE TITLE
InfluxDbWriter attempts to create a Point with no value/measurement 

### ISSUE THREAD

**Issue by a-wildman** [jmxtrans/jmxtrans#669]
Given the following config:

{
  "servers" : [ {
    "host" : "foo.bar.com",
    "port" : "1234",
    "queries" : [ {
      "obj" : "java.lang:type=Memory",
      "attr" : [ "HeapMemoryUsage", "NonHeapMemoryUsage" ],
      "outputWriters" : [
      {
        "@class" : "com.googlecode.jmxtrans.model.output.InfluxDbWriterFactory",
        "url" : "http://baz.bar.com:8086/",
        "username" : "foo",
        "password" : "bar",
        "database" : "jmx"
      } ]
    } ]
  } ]
}

Fails with:

2018-04-23 14:24:53 [jmxtrans-query-0] level com.googlecode.jmxtrans.model.Query [Query.java:227] - Executing queryName [java.lang:type=Memory] from query [Query(objectName=java.lang:type=Memory, keys=[], attr=[HeapMemoryUsage, NonHeapMemoryUsage], typeNames=[], resultAlias=null, useObjDomainAsKey=false, allowDottedKeys=false, useAllTypeNames=false, outputWriterInstances=[com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter@2a2ced2c])]

2018-04-23 14:24:53 [jmxtrans-result-0] level com.googlecode.jmxtrans.model.output.InfluxDbWriter [InfluxDbWriter.java:177] - Query result: Result(attributeName=HeapMemoryUsage, className=sun.management.MemoryImpl, objDomain=java.lang, typeName=type=Memory, valuePath=[committed], value=30064771072, epoch=1524518693336, keyAlias=null)

2018-04-23 14:24:53 [jmxtrans-result-0] level com.googlecode.jmxtrans.jmx.ResultProcessor [ResultProcessor.java:65] - Could not write results [Result(attributeName=HeapMemoryUsage, className=sun.management.MemoryImpl, objDomain=java.lang, typeName=type=Memory, valuePath=[committed], value=30064771072, epoch=1524518693336, keyAlias=null), Result(attributeName=HeapMemoryUsage, className=sun.management.MemoryImpl, objDomain=java.lang, typeName=type=Memory, valuePath=[init], value=8589934592, epoch=1524518693336, keyAlias=null), Result(attributeName=HeapMemoryUsage, className=sun.management.MemoryImpl, objDomain=java.lang, typeName=type=Memory, valuePath=[max], value=30064771072, epoch=1524518693336, keyAlias=null), Result(attributeName=HeapMemoryUsage, className=sun.management.MemoryImpl, objDomain=java.lang, typeName=type=Memory, valuePath=[used], value=10972339024, epoch=1524518693336, keyAlias=null), Result(attributeName=NonHeapMemoryUsage, className=sun.management.MemoryImpl, objDomain=java.lang, typeName=type=Memory, valuePath=[committed], value=1931264000, epoch=1524518693336, keyAlias=null), Result(attributeName=NonHeapMemoryUsage, className=sun.management.MemoryImpl, objDomain=java.lang, typeName=type=Memory, valuePath=[init], value=2555904, epoch=1524518693336, keyAlias=null), Result(attributeName=NonHeapMemoryUsage, className=sun.management.MemoryImpl, objDomain=java.lang, typeName=type=Memory, valuePath=[max], value=-1, epoch=1524518693336, keyAlias=null), Result(attributeName=NonHeapMemoryUsage, className=sun.management.MemoryImpl, objDomain=java.lang, typeName=type=Memory, valuePath=[used], value=975433104, epoch=1524518693336, keyAlias=null)] of query Query(objectName=java.lang:type=Memory, keys=[], attr=[HeapMemoryUsage, NonHeapMemoryUsage], typeNames=[], resultAlias=null, useObjDomainAsKey=false, allowDottedKeys=false, useAllTypeNames=false, outputWriterInstances=[com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter@2a2ced2c]) to output writer com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter@2a2ced2c
java.lang.IllegalArgumentException: Expecting a non-empty string for measurement
	at org.influxdb.impl.Preconditions.checkNonEmptyString(Preconditions.java:22)
	at org.influxdb.dto.Point$Builder.build(Point.java:202)
	at com.googlecode.jmxtrans.model.output.InfluxDbWriter.doWrite(InfluxDbWriter.java:195)
	at com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter.doWrite(ResultTransformerOutputWriter.java:53)
	at com.googlecode.jmxtrans.jmx.ResultProcessor$1.run(ResultProcessor.java:63)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Confirmed that values are being read correctly from the target by using a com.googlecode.jmxtrans.model.output.KeyOutWriter in parallel and sending that to file.

jmxtrans package info follows:

 Package: jmxtrans
 Version: 270
 Section: admin
 Priority: optional
 Architecture: all
 Depends: debconf (>= 0.5) | debconf-2.0
 Recommends: python-yaml
 Suggests: java2-runtime
 Installed-Size: 20089
 Maintainer: Pushkar Raste <praste@bloomberg.net, pushkar.raste@gmail.com>
 Description: 270 - jmxtrans
  dependency package, installs jmxtrans
 Homepage: http://www.jmxtrans.org/jmxtrans

Also tried with version 269, with same result.  Downloaded from http://central.maven.org/maven2/org/jmxtrans/jmxtrans/270/jmxtrans-270.deb

**Comment by jarek-przygodzki** [comment]
The workaround is to set _resultAlias_: 
```
    "queries" : [ {
      "obj" : "java.lang:type=Memory",
      "attr" : [ "HeapMemoryUsage", "NonHeapMemoryUsage" ],
      "resultAlias" : "jvmMemory",
```
