### ISSUE TITLE
jmxtrans JBOSS integration

### ISSUE THREAD

**Issue by nadavsteindler** [jmxtrans/jmxtrans#683]
So I'm trying to get jmxtrans to connect to JMX in an instance of JBOSS application server.
In JBOSS, you don't just enter a host and port, rather a more complex URL like  service:jmx:remote+http://172.17.37.169:8990
(see https://dzone.com/articles/remote-jmx-access-wildfly-or)

This works for jconsole, but I'm having trouble getting it to work with jmxtrans. In the jmxtrans json config file I put:
{
  "servers" : [ {
    "port" : "8990",
    "host" : " service:jmx:remote+http://172.17.37.169",
    "queries" : [ {
      "outputWriters" : [ {
        "@class" : "com.googlecode.jmxtrans.model.output.StdOutWriter",
        "settings" : {
        }
      } ],
      "obj" : "java.lang:type=Memory",
      "attr" : [ "HeapMemoryUsage" ]
    } ],
    "numQueryThreads" : 2
  } ]
}

But when I run jmxtrans, I get an exception:
java.lang.NumberFormatException: For input string: "jmx:remote+http:"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at com.sun.jndi.url.rmi.rmiURLContext.getRootURLContext(rmiURLContext.java:102)
        at com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:202)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)
        at javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1955)
        at javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1922)
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:287)
        at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
        at com.googlecode.jmxtrans.model.Server.getServerConnection(Server.java:347)
        at com.googlecode.jmxtrans.connections.MBeanServerConnectionFactory.makeObject(MBeanServerConnectionFactory.java:46)
        at com.googlecode.jmxtrans.connections.MBeanServerConnectionFactory.makeObject(MBeanServerConnectionFactory.java:33)
        at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220)
        at com.googlecode.jmxtrans.model.Server.execute(Server.java:279)
        at com.googlecode.jmxtrans.jmx.ProcessQueryThread.run(ProcessQueryThread.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by nlaurent9816** [comment]
Yes, in your configuration, you can use the "url" configuration instead of host + port:

```
{
"servers" : [ {
"url" : " service:jmx:remote+http://172.17.37.169:8990",
"queries" : [ {
...
```

You also need to include a jar with the remote+http connector at startup. You have to run the jar with the ``-a <some.jar>`` argument (``-a`` is for additional jars) or edit the run script. I personnaly use the ``jboss-cli-client.jar`` and it works well.

**Comment by nadavsteindler** [comment]
Awesome! That was my next question. Thank you, sir!
