### ISSUE TITLE
Terminate jmxtrans when it runs into an exception?

### ISSUE THREAD

**Issue by JashG** [jmxtrans/jmxtrans#685]
I am running jmxtrans as a daemon process, as such:

`./jmxtrans start /path-to-config-file.json`

My config file is writing data to Graphite and works fine.

My issue lies within the certain cases that cause jmxtrans to stop writing to Graphite. For example:
  1) issues connecting to graphite server
  2) deleting a config file (even if I specify a different config file in the "start" command)
In these cases, the log file shows that an exception was thrown. However, jmxtrans itself is still running, and I have to manually stop/restart it in order for data to start writing to Graphite again.

Is there a way to automatically terminate jmxtrans when, say, an exception is thrown that causes it to stop writing data? A simple shell script could solve the issue of failing to connect to graphite, but I'm not sure if there is an established approach to take when running into the issue of an exception being thrown. Thanks!

**Comment by gehel** [comment]
It looks like a bug... I'd much prefer to fix the bug rather than having a workaround like restarting jmxtrans. Could you send the log showing the problem?

**Comment by JashG** [comment]
- The following occurs when I start jmxtrans and delete a config file. This happens when the start command doesn't contain a path to a config file, when it contains a path to a different config file, and when it contains a path to the deleted file. (For the most part, this is probably easily avoidable).

2018-06-20 15:00:10 [Thread-3] level com.googlecode.jmxtrans.JmxTransformer [JmxTransformer.java:548] - Configuration file deleted: /var/lib/jmxtrans/testKeyWriter.json
INFO   | jvm 1    | 2018/06/20 15:00:10 | 2018-06-20 15:00:10 [Thread-3] INFO  c.googlecode.jmxtrans.JmxTransformer - Configuration file deleted: /var/lib/jmxtrans/testKeyWriter.json
INFO   | jvm 1    | 2018/06/20 15:00:11 | Exception in thread "Thread-3" java.lang.RuntimeException: javax.management.InstanceAlreadyExistsException: com.googlecode.jmxtrans:Type=JmxTransformerProcess,Name=JmxTransformerProcess
INFO   | jvm 1    | 2018/06/20 15:00:11 | 	at com.googlecode.jmxtrans.util.WatchDir.run(WatchDir.java:106)
INFO   | jvm 1    | 2018/06/20 15:00:11 | Caused by: javax.management.InstanceAlreadyExistsException: com.googlecode.jmxtrans:Type=JmxTransformerProcess,Name=JmxTransformerProcess
INFO   | jvm 1    | 2018/06/20 15:00:11 | 	at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
INFO   | jvm 1    | 2018/06/20 15:00:11 | 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
INFO   | jvm 1    | 2018/06/20 15:00:11 | 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
INFO   | jvm 1    | 2018/06/20 15:00:11 | 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
INFO   | jvm 1    | 2018/06/20 15:00:11 | 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
INFO   | jvm 1    | 2018/06/20 15:00:11 | 	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
INFO   | jvm 1    | 2018/06/20 15:00:11 | 	at com.googlecode.jmxtrans.JmxTransformer.registerMBeans(JmxTransformer.java:402)
INFO   | jvm 1    | 2018/06/20 15:00:11 | 	at com.googlecode.jmxtrans.JmxTransformer.startupSystem(JmxTransformer.java:324)
INFO   | jvm 1    | 2018/06/20 15:00:11 | 	at com.googlecode.jmxtrans.JmxTransformer.fileDeleted(JmxTransformer.java:551)
INFO   | jvm 1    | 2018/06/20 15:00:11 | 	at com.googlecode.jmxtrans.util.WatchDir.run(WatchDir.java:98)

- In the case where jmxtrans can't connect to Graphite, this exception is thrown multiple times per second:

2018-06-21 10:09:43 [Stormpot-pool-4-thread-1] level com.googlecode.jmxtrans.model.output.support.pool.RetryingAllocator [RetryingAllocator.java:77] - Error allocating slot
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.googlecode.jmxtrans.model.output.support.pool.SocketAllocator.allocate(SocketAllocator.java:61)
	at com.googlecode.jmxtrans.model.output.support.pool.SocketAllocator.allocate(SocketAllocator.java:37)
	at com.googlecode.jmxtrans.model.output.support.pool.RetryingAllocator$2.call(RetryingAllocator.java:89)
	at com.googlecode.jmxtrans.model.output.support.pool.RetryingAllocator$2.call(RetryingAllocator.java:86)
	at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(AttemptTimeLimiters.java:78)
	at com.github.rholder.retry.Retryer.call(Retryer.java:160)
	at com.googlecode.jmxtrans.model.output.support.pool.RetryingAllocator.allocate(RetryingAllocator.java:86)
	at stormpot.ReallocatingAdaptor.allocate(ReallocatingAdaptor.java:37)
	at stormpot.BAllocThread.alloc(BAllocThread.java:225)
	at stormpot.BAllocThread.increaseSizeByAllocating(BAllocThread.java:131)
	at stormpot.BAllocThread.replenishPool(BAllocThread.java:106)
	at stormpot.BAllocThread.continuouslyReplenishPool(BAllocThread.java:88)
	at stormpot.BAllocThread.run(BAllocThread.java:80)
	at java.lang.Thread.run(Thread.java:748)

There may be other similar scenarios, this is just what I have run into.

**Comment by afn** [comment]
I've encountered the issue with `javax.management.InstanceAlreadyExistsException` as well, and there are two underlying issues that need to be addressed:

1. The `startupSystem()` method shouldn't attempt to re-register mbeans (or alternatively, they should get unregistered and reregistered)
2. An exception in the watchDir handler should cause the process to exit with a non-zero status. Given that there are other scenarios as well where threads die with uncaught exceptions (as you've shown), I think the right thing to do is to register a global uncaught exception handler to exit.

I'll follow up with a PR shortly.

**Comment by cedrico2016** [comment]
I'm starting JmxTrans whit the option `-j $JSON_DIR` where the JSON configs are in the JSON_DIR folder.
i'm currently getting the same exception  
`Exception in thread "Thread-3" java.lang.RuntimeException: javax.management.InstanceAlreadyExistsException: com.googlecode.jmxtrans:Type=JmxTransformerProcess,Name=JmxTransformerProcess
--
  | at com.googlecode.jmxtrans.util.WatchDir.run(WatchDir.java:106) `

also when i'm just adding a new configuration.

**Comment by Zophar78** [comment]
This one is fixed by #731
