### ISSUE TITLE
Json file parsing is not working

### ISSUE THREAD

**Issue by abeyaert** [jmxtrans/jmxtrans#702]
Hello,

I try to get metrics  from a kafka broker and put them into InfluxDb , so I have the following configuration in my json file to run jmxtrans. But when I start it, I get this error and don't understand where it should come from. 

The json file:
`
{

  "servers" : [ {	
    "alias" : "test",
    "port" : "9000",
    "host" : "ip_address",
    "ssl" : true,
    "queries" : [ {
      "obj" : "java.lang:type=Memory",
      "attr" : [ "HeapMemoryUsage", "NonHeapMemoryUsage" ],
      "resultAlias":"jvmMemory",
      "outputWriters" : [ {
        "@class" : "com.googlecode.jmxtrans.model.output.InfluxDbWriterFactory",
        "url" : "http://ip_address:8004/",
        "username" : "admin",
        "password" : "pwd",
        "database" : "jmxDB",
        "tags"     : {"application" : "kafka"},
	 "resultTags":["typeName","className"],
        "retentionPolicy":"default",
        "writeConsistency":"ALL",
        "createDatabase":"true",
        "reportJmxPortAsTag":"true"
      } ]
   } ]
}]
}`

and here is the error I get from the log file:

`Exception in thread "main" com.googlecode.jmxtrans.exceptions.LifecycleException: com.googlecode.jmxtrans.exceptions.LifecycleException: Error parsing json: jvm.json
        at com.googlecode.jmxtrans.JmxTransformer.start(JmxTransformer.java:187)
        at com.googlecode.jmxtrans.JmxTransformer.doMain(JmxTransformer.java:155)
        at com.googlecode.jmxtrans.JmxTransformer.main(JmxTransformer.java:147)
Caused by: com.googlecode.jmxtrans.exceptions.LifecycleException: Error parsing json: jvm.json
        at com.googlecode.jmxtrans.ConfigurationParser.parseServers(ConfigurationParser.java:62)
        at com.googlecode.jmxtrans.JmxTransformer.processFilesIntoServers(JmxTransformer.java:365)
        at com.googlecode.jmxtrans.JmxTransformer.startupSystem(JmxTransformer.java:322)
        at com.googlecode.jmxtrans.JmxTransformer.start(JmxTransformer.java:183)
        ... 2 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.googlecode.jmxtrans.model.output.InfluxDbWriterFactory, problem: null
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.googlecode.jmxtrans.model.JmxProcess["servers"]->java.util.ArrayList[0]->com.googlecode.jmxtrans.model.Server["queries"]->java.util.ArrayList[0]->com.googlecode.jmxtrans.model.Query["outputWriters"]->java.util.ArrayList[0])
`

Thanks for your support!

**Comment by nlaurent9816** [comment]
Hello,

I cannot reproduce this bug. Your config give me another bug (`@class` instead of `@Class`) but nothing with the same logs.
It may also be an invisible character in the file.
 
The answer should be here:
`com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.googlecode.jmxtrans.model.output.InfluxDbWriterFactory, problem: null `
But this `problem: null` isn't normal. It should show the cause of the problem instead of `null`.

I have some questions:
Can you give the version you are running? 
Have you just downloaded it or compiled yourself?
Does it works with other outputWriters? (StdOutWriter, Slf4JOutputWriter, ...)

**Comment by abeyaert** [comment]
Hello,

I am currently running the last version of jmxtrans, 270.
I just downloaded it and made it run in a directory, because I didn't have rights to run scripts with usial installation as described in the wiki.
In the directory, I have the startup script (jmxtrans.sh), the jar file (jmxtrans_270_all.jar) and the json file.
Until now, we tried to make it work with SSL feature of jmxtrans, but didn't succeed so far.
Finally we remove the SSL configuration from the kafka broker, where we get the metrics.
Now it works with the KeyOut writer, but the final goal is to put the metrics into an Influx Database, so we configured the json to do that:

{
  "servers" : [ {
    "port" : "9000",
    "host" : "ip_address",
    "queries" : [ {
      "obj" : "java.lang:type=Memory",
      "attr" : [ "HeapMemoryUsage", "NonHeapMemoryUsage" ],
      "resultAlias":"jvmMemory",
      "outputWriters" : [ {
        "@class" : "com.googlecode.jmxtrans.model.output.InfluxDbWriterFactory",
        "url" : "http://ip_address:8004/",
        "username" : "admin",
        "password" : "password",
        "database" : "jmxDB",
        "tags"     : {"application" : "kafka"},
        "retentionPolicy":"default",
        "writeConsistency":"ALL"
      } ]
    } ]
  } ]
}

The thing is, in the log generated we get the following:

[jmxtrans-result-0] level com.googlecode.jmxtrans.jmx.ResultProcessor [ResultProcessor.java:65] - Could not write results [Result(attributeName=HeapMemoryUsage, className=sun.management.MemoryImpl, objDomain=java.lang, typeName=type=Memory, valuePath=[committed], value=67108864000, epoch=1537340541308, keyAlias=jvmMemory), Result(attributeName=HeapMemoryUsage, className=sun.management.MemoryImpl, objDomain=java.lang, typeName=type=Memory, valuePath=[init], value=67108864000, epoch=1537340541308, keyAlias=jvmMemory), Result(attributeName=HeapMemoryUsage, className=sun.management.MemoryImpl, objDomain=java.lang, typeName=type=Memory, valuePath=[max], value=67108864000, epoch=1537340541308, keyAlias=jvmMemory), Result(attributeName=HeapMemoryUsage, className=sun.management.MemoryImpl, objDomain=java.lang, typeName=type=Memory, valuePath=[used], value=21213744264, epoch=1537340541308, keyAlias=jvmMemory), Result(attributeName=NonHeapMemoryUsage, className=sun.management.MemoryImpl, objDomain=java.lang, typeName=type=Memory, valuePath=[committed], value=75956224, epoch=1537340541308, keyAlias=jvmMemory), Result(attributeName=NonHeapMemoryUsage, className=sun.management.MemoryImpl, objDomain=java.lang, typeName=type=Memory, valuePath=[init], value=2555904, epoch=1537340541308, keyAlias=jvmMemory), Result(attributeName=NonHeapMemoryUsage, className=sun.management.MemoryImpl, objDomain=java.lang, typeName=type=Memory, valuePath=[max], value=-1, epoch=1537340541308, keyAlias=jvmMemory), Result(attributeName=NonHeapMemoryUsage, className=sun.management.MemoryImpl, objDomain=java.lang, typeName=type=Memory, valuePath=[used], value=74865416, epoch=1537340541308, keyAlias=jvmMemory)] of query Query(objectName=java.lang:type=Memory, keys=[], attr=[HeapMemoryUsage, NonHeapMemoryUsage], typeNames=[], resultAlias=jvmMemory, useObjDomainAsKey=false, allowDottedKeys=false, useAllTypeNames=false, outputWriterInstances=[com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter@5c924fc2]) to output writer com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter@5c924fc2
org.influxdb.InfluxDBIOException: java.net.ProtocolException: Unexpected status line: jmxtrans.jmx.ResultProcessor$1.run(ResultProcessor.java:63)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ProtocolException: Unexpected status line: oggingInterceptor.intercept(HttpLoggingInterceptor.java:144)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
	at org.influxdb.impl.InfluxDBImpl.ping(InfluxDBImpl.java:240)
`

So now I don't really know if we should produce a script to get metrics from the file generated with KeyOut Writer and put them into the database, or try to solve this error, but I found anything about it.

Do you have an idea regarding my current configuration ?

Thanks!

**Comment by nlaurent9816** [comment]
The problem seems to be between the InfluxDB module used by jmxtrans and the InfluxDB server. The response given by the server is not well formatted.
It may be an old version of InfluxDB with an old protocol. Can you give me the version of your InfluxDB? (you can have it with the `influx -version `command or with `curl -sL -I influx_addr:influx_port/ping`)
I see in the config that you're using the 8004 port for InfluxDB. The default port is 8086, have you changed it?
It can also be a proxy problem. Have you a proxy between jmxtrans and InfluxDB?

**Comment by abeyaert** [comment]
These are the results of the two commands.

curl -sL -I influx_addr:influx_port/ping : 
HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 9e417fa2-bc06-11e8-8007-000000000000
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.4.2
X-Request-Id: 9e417fa2-bc06-11e8-8007-000000000000
Date: Wed, 19 Sep 2018 12:22:04 GMT

influx -version
InfluxDB shell version: 1.4.2

The port 8004 we are using has also been configure to communicate with SSL, would it be a factor on the JMXTrans side ?

**Comment by nlaurent9816** [comment]
GOT IT ! i's a SSL issue : you have `"url" : "http://ip_address:8004/",` in your config, so the client didn't expect SSL connection.
You can change your JMXTrans config with  `"url" : "https://ip_address:8004/",` (I hope you have a valid certificate) or disable https in your influxDB.

**Comment by abeyaert** [comment]
Allright it looks better, thank you ! I totally forget this detail about the "s" in the URL...

I now have this issue:

Could not write results [Result(attributeName=HeapMemoryUsage, className=sun.management.MemoryImpl, objDomain=java.lang, typeName=type=Memory, valuePath=[committed], value=67108864000, epoch=1537366052940, keyAlias=jvmMemory), Result(attributeName=HeapMemoryUsage, className=sun.management.MemoryImpl, objDomain=java.lang, typeName=type=Memory, valuePath=[init], value=67108864000, epoch=1537366052940, keyAlias=jvmMemory), Result(attributeName=HeapMemoryUsage, className=sun.management.MemoryImpl, objDomain=java.lang, typeName=type=Memory, valuePath=[max], value=67108864000, epoch=1537366052940, keyAlias=jvmMemory), Result(attributeName=HeapMemoryUsage, className=sun.management.MemoryImpl, objDomain=java.lang, typeName=type=Memory, valuePath=[used], value=5601336280, epoch=1537366052940, keyAlias=jvmMemory), Result(attributeName=NonHeapMemoryUsage, className=sun.management.MemoryImpl, objDomain=java.lang, typeName=type=Memory, valuePath=[committed], value=76480512, epoch=1537366052940, keyAlias=jvmMemory), Result(attributeName=NonHeapMemoryUsage, className=sun.management.MemoryImpl, objDomain=java.lang, typeName=type=Memory, valuePath=[init], value=2555904, epoch=1537366052940, keyAlias=jvmMemory), Result(attributeName=NonHeapMemoryUsage, className=sun.management.MemoryImpl, objDomain=java.lang, typeName=type=Memory, valuePath=[max], value=-1, epoch=1537366052940, keyAlias=jvmMemory), Result(attributeName=NonHeapMemoryUsage, className=sun.management.MemoryImpl, objDomain=java.lang, typeName=type=Memory, valuePath=[used], value=75341320, epoch=1537366052940, keyAlias=jvmMemory)] of query Query(objectName=java.lang:type=Memory, keys=[], attr=[HeapMemoryUsage, NonHeapMemoryUsage], typeNames=[], resultAlias=jvmMemory, useObjDomainAsKey=false, allowDottedKeys=false, useAllTypeNames=false, outputWriterInstances=[com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter@5c924fc2]) to output writer com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter@5c924fc2

org.influxdb.InfluxDBIOException: javax.net.ssl.SSLPeerUnverifiedException: Hostname InfluxDBIPAddress not verified:certificate: 
    DN: CN=..., OU=..., O=..., L=..., ST=..., C=...

I guess it should be an issue regarding the certificate, do you have a suggestion ?

**Comment by nlaurent9816** [comment]
The certificate used by InfluxDB is not trusted by java (probably a self signed cert).
I don't think you can easly skip the verification, but you can add the certificate to the Java TrustStore (where all java apps store their trusted certificates).

This link may help : [https://doc.nuxeo.com/nxdoc/trust-store-and-key-store-configuration/](https://doc.nuxeo.com/nxdoc/trust-store-and-key-store-configuration/)

**Comment by abeyaert** [comment]
Allright, now it works ! I inserted a wrong url format in the JSON file at the end.
I can get metrics from the InfluxDB example on the wiki, but don't succeed yet to get metrics from kafka type, I'll have to figure out where is the issue in my definition of the "obj" value... 
If you know a json file where kafka metrics have been configured and writing works properly, please let me know.
Otherwise my issue regarding connectivity is solved.
