### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by HouwelingFrank** [jmxtrans/jmxtrans#755]
Dear all,

When I start the latest jmxtrans docker container me and my colleague get an java.lang.UnsatisfiedLinkError error. I took the image from the latest from docker hub:
https://hub.docker.com/r/jmxtrans/jmxtrans. Does anyone have a suggestion to solve this?

I the docker container with the following command on my windows machine, with a volume defined where I have my config.json file:
_docker run -it -v C:/data/volume_jmxtrans:/var/lib/jmxtrans --env SECONDS_BETWEEN_RUNS=30 --env HEAP_SIZE=1024 -P jmxtrans/jmxtrans_

The logging including the error:
OpenJDK 64-Bit Server VM warning: ignoring option PermSize=384m; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
2019-08-28 09:19:15 [main] INFO  org.quartz.impl.StdSchedulerFactory - Using default implementation for ThreadExecutor
2019-08-28 09:19:15 [main] INFO  org.quartz.core.SchedulerSignalerImpl - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2019-08-28 09:19:15 [main] INFO  org.quartz.core.QuartzScheduler - Quartz Scheduler v.1.8.6 created.
2019-08-28 09:19:15 [main] INFO  org.quartz.simpl.RAMJobStore - RAMJobStore initialized.
2019-08-28 09:19:15 [main] INFO  org.quartz.core.QuartzScheduler - Scheduler meta-data: Quartz Scheduler (v1.8.6) 'ServerScheduler' with instanceId '23ee1f28259f1566983955096'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2019-08-28 09:19:15 [main] INFO  org.quartz.impl.StdSchedulerFactory - Quartz scheduler 'ServerScheduler' initialized from an externally opened InputStream.
2019-08-28 09:19:15 [main] INFO  org.quartz.impl.StdSchedulerFactory - Quartz scheduler version: 1.8.6
2019-08-28 09:19:15 [main] INFO  org.quartz.core.QuartzScheduler - JobFactory set to: com.googlecode.jmxtrans.guice.GuiceJobFactory@26e356f0
2019-08-28 09:19:15 [main] INFO  com.googlecode.jmxtrans.JmxTransformer - Starting Jmxtrans on : /var/lib/jmxtrans
2019-08-28 09:19:15 [main] INFO  org.quartz.core.QuartzScheduler - Scheduler ServerScheduler_$_23ee1f28259f1566983955096 started.
java.lang.UnsatisfiedLinkError: /tmp/jpathwatch-nativelib-v-0-95-libjpathwatch-native.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/jpathwatch-nativelib-v-0-95-libjpathwatch-native.so)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at name.pachler.nio.file.impl.NativeLibLoader.extractAndLoadLibrary(NativeLibLoader.java:407)
        at name.pachler.nio.file.impl.NativeLibLoader.loadLibrary(NativeLibLoader.java:257)
        at name.pachler.nio.file.impl.LinuxPathWatchService.<clinit>(LinuxPathWatchService.java:105)
        at name.pachler.nio.file.ext.Bootstrapper.newWatchService(Bootstrapper.java:80)
        at name.pachler.nio.file.FileSystems$1.newWatchService(FileSystems.java:40)
        at com.googlecode.jmxtrans.util.WatchDir.<init>(WatchDir.java:56)
        at com.googlecode.jmxtrans.JmxTransformer.startupWatchdir(JmxTransformer.java:298)
        at com.googlecode.jmxtrans.JmxTransformer.start(JmxTransformer.java:181)
        at com.googlecode.jmxtrans.JmxTransformer.doMain(JmxTransformer.java:155)
        at com.googlecode.jmxtrans.JmxTransformer.main(JmxTransformer.java:147)
java.lang.UnsatisfiedLinkError: /tmp/jpathwatch-nativelib-v-0-95-8404108935848086502libjpathwatch-native.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/jpathwatch-nativelib-v-0-95-8404108935848086502libjpathwatch-native.so)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at name.pachler.nio.file.impl.NativeLibLoader.extractAndLoadLibrary(NativeLibLoader.java:407)
        at name.pachler.nio.file.impl.NativeLibLoader.loadLibrary(NativeLibLoader.java:267)
        at name.pachler.nio.file.impl.LinuxPathWatchService.<clinit>(LinuxPathWatchService.java:105)
        at name.pachler.nio.file.ext.Bootstrapper.newWatchService(Bootstrapper.java:80)
        at name.pachler.nio.file.FileSystems$1.newWatchService(FileSystems.java:40)
        at com.googlecode.jmxtrans.util.WatchDir.<init>(WatchDir.java:56)
        at com.googlecode.jmxtrans.JmxTransformer.startupWatchdir(JmxTransformer.java:298)
        at com.googlecode.jmxtrans.JmxTransformer.start(JmxTransformer.java:181)
        at com.googlecode.jmxtrans.JmxTransformer.doMain(JmxTransformer.java:155)
        at com.googlecode.jmxtrans.JmxTransformer.main(JmxTransformer.java:147)
java.lang.UnsatisfiedLinkError: no jpathwatch-native in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at name.pachler.nio.file.impl.NativeLibLoader.loadDefaultLibrary(NativeLibLoader.java:84)
        at name.pachler.nio.file.impl.NativeLibLoader.loadLibrary(NativeLibLoader.java:277)
        at name.pachler.nio.file.impl.LinuxPathWatchService.<clinit>(LinuxPathWatchService.java:105)
        at name.pachler.nio.file.ext.Bootstrapper.newWatchService(Bootstrapper.java:80)
        at name.pachler.nio.file.FileSystems$1.newWatchService(FileSystems.java:40)
        at com.googlecode.jmxtrans.util.WatchDir.<init>(WatchDir.java:56)
        at com.googlecode.jmxtrans.JmxTransformer.startupWatchdir(JmxTransformer.java:298)
        at com.googlecode.jmxtrans.JmxTransformer.start(JmxTransformer.java:181)
        at com.googlecode.jmxtrans.JmxTransformer.doMain(JmxTransformer.java:155)
        at com.googlecode.jmxtrans.JmxTransformer.main(JmxTransformer.java:147)
java.lang.UnsatisfiedLinkError: /tmp/jpathwatch-nativelib-v-0-95-libjpathwatch-native.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/jpathwatch-nativelib-v-0-95-libjpathwatch-native.so)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at name.pachler.nio.file.impl.NativeLibLoader.extractAndLoadLibrary(NativeLibLoader.java:407)
        at name.pachler.nio.file.impl.NativeLibLoader.loadLibrary(NativeLibLoader.java:257)
        at name.pachler.nio.file.impl.Unix.<clinit>(Unix.java:86)
        at name.pachler.nio.file.impl.LinuxPathWatchService.<init>(LinuxPathWatchService.java:211)
        at name.pachler.nio.file.ext.Bootstrapper.newWatchService(Bootstrapper.java:80)
        at name.pachler.nio.file.FileSystems$1.newWatchService(FileSystems.java:40)
        at com.googlecode.jmxtrans.util.WatchDir.<init>(WatchDir.java:56)
        at com.googlecode.jmxtrans.JmxTransformer.startupWatchdir(JmxTransformer.java:298)
        at com.googlecode.jmxtrans.JmxTransformer.start(JmxTransformer.java:181)
        at com.googlecode.jmxtrans.JmxTransformer.doMain(JmxTransformer.java:155)
        at com.googlecode.jmxtrans.JmxTransformer.main(JmxTransformer.java:147)
java.lang.UnsatisfiedLinkError: /tmp/jpathwatch-nativelib-v-0-95-7444898884185850588libjpathwatch-native.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/jpathwatch-nativelib-v-0-95-7444898884185850588libjpathwatch-native.so)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at name.pachler.nio.file.impl.NativeLibLoader.extractAndLoadLibrary(NativeLibLoader.java:407)
        at name.pachler.nio.file.impl.NativeLibLoader.loadLibrary(NativeLibLoader.java:267)
        at name.pachler.nio.file.impl.Unix.<clinit>(Unix.java:86)
        at name.pachler.nio.file.impl.LinuxPathWatchService.<init>(LinuxPathWatchService.java:211)
        at name.pachler.nio.file.ext.Bootstrapper.newWatchService(Bootstrapper.java:80)
        at name.pachler.nio.file.FileSystems$1.newWatchService(FileSystems.java:40)
        at com.googlecode.jmxtrans.util.WatchDir.<init>(WatchDir.java:56)
        at com.googlecode.jmxtrans.JmxTransformer.startupWatchdir(JmxTransformer.java:298)
        at com.googlecode.jmxtrans.JmxTransformer.start(JmxTransformer.java:181)
        at com.googlecode.jmxtrans.JmxTransformer.doMain(JmxTransformer.java:155)
        at com.googlecode.jmxtrans.JmxTransformer.main(JmxTransformer.java:147)
java.lang.UnsatisfiedLinkError: no jpathwatch-native in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at name.pachler.nio.file.impl.NativeLibLoader.loadDefaultLibrary(NativeLibLoader.java:84)
        at name.pachler.nio.file.impl.NativeLibLoader.loadLibrary(NativeLibLoader.java:277)
        at name.pachler.nio.file.impl.Unix.<clinit>(Unix.java:86)
        at name.pachler.nio.file.impl.LinuxPathWatchService.<init>(LinuxPathWatchService.java:211)
        at name.pachler.nio.file.ext.Bootstrapper.newWatchService(Bootstrapper.java:80)
        at name.pachler.nio.file.FileSystems$1.newWatchService(FileSystems.java:40)
        at com.googlecode.jmxtrans.util.WatchDir.<init>(WatchDir.java:56)
        at com.googlecode.jmxtrans.JmxTransformer.startupWatchdir(JmxTransformer.java:298)
        at com.googlecode.jmxtrans.JmxTransformer.start(JmxTransformer.java:181)
        at com.googlecode.jmxtrans.JmxTransformer.doMain(JmxTransformer.java:155)
        at com.googlecode.jmxtrans.JmxTransformer.main(JmxTransformer.java:147)
Aug 28, 2019 9:19:15 AM name.pachler.nio.file.ext.Bootstrapper newWatchService
WARNING: null
java.lang.UnsatisfiedLinkError: name.pachler.nio.file.impl.Unix.getIntDefine(Ljava/lang/String;)I
        at name.pachler.nio.file.impl.Unix.getIntDefine(Native Method)
        at name.pachler.nio.file.impl.Unix.<clinit>(Unix.java:87)
        at name.pachler.nio.file.impl.LinuxPathWatchService.<init>(LinuxPathWatchService.java:211)
        at name.pachler.nio.file.ext.Bootstrapper.newWatchService(Bootstrapper.java:80)
        at name.pachler.nio.file.FileSystems$1.newWatchService(FileSystems.java:40)
        at com.googlecode.jmxtrans.util.WatchDir.<init>(WatchDir.java:56)
        at com.googlecode.jmxtrans.JmxTransformer.startupWatchdir(JmxTransformer.java:298)
        at com.googlecode.jmxtrans.JmxTransformer.start(JmxTransformer.java:181)
        at com.googlecode.jmxtrans.JmxTransformer.doMain(JmxTransformer.java:155)
        at com.googlecode.jmxtrans.JmxTransformer.main(JmxTransformer.java:147)

**Comment by gerardo** [comment]
I'm hitting the same error as well. I started the container like this to get a console and try some things out: `docker run -it jmxtrans/jmxtrans sh`. Once inside, I checked the state of the links, and it matches [this](https://stackoverflow.com/a/55568352/76833). The solution is to install gcompat like this: `apk add --no-cache gcompat`.

It would be great if we could get this fixed in the docker image 🙏 .

**Comment by gerardo** [comment]
@gehel as per https://github.com/jmxtrans/jmxtrans/issues/636, would you be willing to review a PR fixing this if I submit it? I see there are around 31 open PRs right now, some dating all the way to 2015 :(

**Comment by gquintana** [comment]
This issue is fixed is it?
