### ISSUE TITLE
jmxtrans-examples code doesn't work

### ISSUE THREAD

**Issue by cleverpig** [jmxtrans/jmxtrans#757]
I run the main method which in com.googlecode.jmxtrans.example.Graphite, and throw exception, cause pool is null. But I can't find out how to build jmxpool.

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
	at com.googlecode.jmxtrans.model.Server.<init>(Server.java:270)
	at com.googlecode.jmxtrans.model.Server.<init>(Server.java:211)
	at com.googlecode.jmxtrans.model.Server$Builder.build(Server.java:585)
	at com.googlecode.jmxtrans.example.Graphite.main(Graphite.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

And I'd look Server construct method, there is a checkNotNull for pool.

```
private Server(
			String alias,
			String pid,
			String host,
			String port,
			String username,
			String password,
			String protocolProviderPackages,
			String url,
			String cronExpression,
			Integer runPeriodSeconds,
			Integer numQueryThreads,
			boolean local,
			boolean ssl,
			List<Query> queries,
			List<OutputWriterFactory> outputWriterFactories,
			List<OutputWriter> outputWriters,
			KeyedObjectPool<JmxConnectionProvider, JMXConnection> pool) {

		checkArgument(pid != null || url != null || host != null,
				"You must provide the pid or the [url|host and port]");
		checkArgument(!(pid != null && (url != null || host != null)),
				"You must provide the pid OR the url, not both");

		this.alias = alias;
		this.pid = pid;
		this.port = port;
		this.username = username;
		this.password = password;
		this.protocolProviderPackages = protocolProviderPackages;
		this.url = url;
		this.cronExpression = cronExpression;
		if (!isNullOrEmpty(cronExpression)) {
			logger.warn("cronExpression is deprecated, please use runPeriodSeconds instead.");
		}

		this.runPeriodSeconds = runPeriodSeconds;
		this.numQueryThreads = firstNonNull(numQueryThreads, 0);
		this.local = local;
		this.ssl = ssl;
		this.queries = copyOf(queries);

		// when connecting in local, we cache the host after retrieving it from the network card
		if(pid != null) {
			try {
				this.host = InetAddress.getLocalHost().getHostName();
			} catch (UnknownHostException e) {
				// should work, so just throw a runtime if it doesn't
				throw new RuntimeException(e);
			}
		}
		else {
			this.host = host;
		}
		this.pool = checkNotNull(pool);
		this.outputWriterFactories = ImmutableList.copyOf(firstNonNull(outputWriterFactories, ImmutableList.<OutputWriterFactory>of()));
		this.outputWriters = ImmutableList.copyOf(firstNonNull(outputWriters, ImmutableList.<OutputWriter>of()));
		this.id = String.format("%s_%s_%s", host, port, pid);
	}
```

**Comment by cleverpig** [comment]
I'd look Server construct method, there is a checkNotNull for pool.

```
private Server(
			String alias,
			String pid,
			String host,
			String port,
			String username,
			String password,
			String protocolProviderPackages,
			String url,
			String cronExpression,
			Integer runPeriodSeconds,
			Integer numQueryThreads,
			boolean local,
			boolean ssl,
			List<Query> queries,
			List<OutputWriterFactory> outputWriterFactories,
			List<OutputWriter> outputWriters,
			KeyedObjectPool<JmxConnectionProvider, JMXConnection> pool) {

		checkArgument(pid != null || url != null || host != null,
				"You must provide the pid or the [url|host and port]");
		checkArgument(!(pid != null && (url != null || host != null)),
				"You must provide the pid OR the url, not both");

		this.alias = alias;
		this.pid = pid;
		this.port = port;
		this.username = username;
		this.password = password;
		this.protocolProviderPackages = protocolProviderPackages;
		this.url = url;
		this.cronExpression = cronExpression;
		if (!isNullOrEmpty(cronExpression)) {
			logger.warn("cronExpression is deprecated, please use runPeriodSeconds instead.");
		}

		this.runPeriodSeconds = runPeriodSeconds;
		this.numQueryThreads = firstNonNull(numQueryThreads, 0);
		this.local = local;
		this.ssl = ssl;
		this.queries = copyOf(queries);

		// when connecting in local, we cache the host after retrieving it from the network card
		if(pid != null) {
			try {
				this.host = InetAddress.getLocalHost().getHostName();
			} catch (UnknownHostException e) {
				// should work, so just throw a runtime if it doesn't
				throw new RuntimeException(e);
			}
		}
		else {
			this.host = host;
		}
		this.pool = checkNotNull(pool);
		this.outputWriterFactories = ImmutableList.copyOf(firstNonNull(outputWriterFactories, ImmutableList.<OutputWriterFactory>of()));
		this.outputWriters = ImmutableList.copyOf(firstNonNull(outputWriters, ImmutableList.<OutputWriter>of()));
		this.id = String.format("%s_%s_%s", host, port, pid);
	}
```

**Comment by cleverpig** [comment]
I added: createPool method

```
public static KeyedObjectPool<JmxConnectionProvider, JMXConnection> createPool() {
	return new GenericKeyedObjectPool<>(new MBeanServerConnectionFactory());
}
```

**Comment by cleverpig** [comment]
I'd fixed one of example Graphite2.java and show it:

```
public class Graphite2 {

	private static final String GW_HOST = "gw";
	private static Logger LOG= LoggerFactory.getLogger(Graphite2.class);

	public static KeyedObjectPool<JmxConnectionProvider, JMXConnection> createPool() {
		return new GenericKeyedObjectPool<>(new MBeanServerConnectionFactory());
	}

	public static void main(String[] args) throws Exception {
		LOG.debug("starting...");

		Server.Builder serverBuilder = Server.builder()
				.setHost("localhost")
				.setPort("15445")
				.setAlias("myPC")
				.setLocal(false)
				.setSsl(false)
				.setPool(createPool())
				.setNumQueryThreads(1);

		ImmutableList<String> typeNames=ImmutableList.of("test");
		GraphiteWriterFactory gwFactory=new GraphiteWriterFactory(
				typeNames,false,"test",
				GW_HOST,2003,"always",0,
				2,10000,10000,"tcp",10000
		);

//		GraphiteWriter2 graphiteWriter2=new GraphiteWriter2(typeNames,"test");

		ResultTransformerOutputWriter<WriterPoolOutputWriter<GraphiteWriter2>> graphiteWriter2=gwFactory.create();
		Set writers=Collections.singleton(graphiteWriter2);
                
               //Notes: you can DIY what you need 
		Query c1Q = Query.builder()
				.setObj("org.apache.flume.channel:type=c1")
				.addAttr("EventPutAttemptCount")
				.addAttr("EventPutSuccessCount")
				.addAttr("EventTakeAttemptCount")
				.addAttr("EventTakeSuccessCount")
//				.addOutputWriterFactory(gwFactory) --outputWriterFactory doesn't work
				.addOutputWriters(writers)
				.setResultAlias("step1.c1")
				.build();
		serverBuilder.addQuery(c1Q);

		Query s1Q = Query.builder()
				.setObj("org.apache.flume.source:type=s1")
				.addAttr("EventAcceptedCount")
				.addAttr("EventReceivedCount")
				.addAttr("GenericProcessingFail")
//				.addOutputWriterFactory(gwFactory)
				.addOutputWriters(writers)
				.setResultAlias("step1.s1")
				.build();
		serverBuilder.addQuery(s1Q);

		Query k1Q = Query.builder()
				.setObj("org.apache.flume.sink:type=k1")
				.addAttr("EventDrainAttemptCount")
				.addAttr("EventDrainSuccessCount")
//				.addOutputWriterFactory(gwFactory)
				.addOutputWriters(writers)
				.setResultAlias("step1.k1")
				.build();
		serverBuilder.addQuery(k1Q);

		JmxProcess process = new JmxProcess(serverBuilder.build());
//		LOG.debug("process json:");
//		new JsonPrinter(System.out).prettyPrint(process);

		JmxTransConfiguration configuration=new JmxTransConfiguration();
		configuration.setQueryProcessorExecutorPoolSize(2);
		configuration.setResultProcessorExecutorPoolSize(2);
		configuration.setQueryProcessorExecutorWorkQueueCapacity(5);
		configuration.setResultProcessorExecutorPoolSize(5);
		configuration.setContinueOnJsonError(false);
		configuration.setRunPeriod(5);

		Injector injector = JmxTransModule.createInjector(configuration);
		JmxTransformer transformer = injector.getInstance(JmxTransformer.class);
		LOG.debug("processing...");
		transformer.executeStandalone(process);

	}
}
```
