### ISSUE TITLE
error when config to elasticsearch

### ISSUE THREAD

**Issue by YiGene** [jmxtrans/jmxtrans#758]
i got below error:  is it because of the version issue..?
use the stdoutput writer do not have such errors

2019-09-05 09:03:53 [main] INFO  org.quartz.core.QuartzScheduler - Scheduler ServerScheduler_$ started.
Exception in thread "main" java.lang.UnsupportedClassVersionError: io/searchbox/action/Action : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:792)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)

**Comment by YiGene** [comment]
java 7only
